### ISSUE TITLE
Create fetch XML query that obtains a contact's projects and PAS statuses

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#1]
Starting with a user's contact ID, try to create the following chained, joined query

- Query the dcp_projectapplicant table to get the contact's assigned project IDs
- From dcp_project table, get project visibility and statuscode=active
- Get the associated PAS packages
- Get the status and visibility of the PAS packages

contact -> projectapplicantteam -> project -> paspackage

**Comment by bfreeds** [comment]
@allthesignals based on what you've learned so far about the web api, do you think there is any value in researching this XML approach?  From what I know so far it seems like there's no difference from using JSON.

**Comment by allthesignals** [comment]
The major differences are that FetchXML:
 - Allow for more complicated querying
 - Allow for more results

Here is an e-mail on this issue:

> This property defines relationship for a lookup Applicant on package entity. Basically Applicant can own one more packages, and that is provided by this relationship. **Expanding this property only works when you retrieve a single dcp_projectapplicant record by guid. It doesn't work when retrieving multiple records via filters, as you tried to do. Moreover expand can only return 50 records at a time.** After that you need to use nextLink to retrieve more. For all those reasons we usually use fetch xml to do nested queries. Rest query is only useful for simple retrieves. You can generate fetch xml from advaned find. Just build your query in advanced find and click download fetch xml.

The main limitation is with expanded record counts. We should be okay with using "nextLink". The reason I'm okay with JSON API is that I believe it's more paradigmatic and consistent with REST conventions and the tooling we're all familiar with.

**Comment by allthesignals** [comment]
I'm going to close for now. There is no doubt about using FetchXML. Here are some old ways of doing it in previous iterations: 

https://github.com/NYCPlanning/deprecated-labs-zap-api/blob/refactor/queries/projects-xmls.js

**Comment by bfreeds** [comment]
@allthesignals this makes sense to close for now, and the info provided above is really helpful.  Agree that we should default to JSON unless we run into complications that would require `FetchXML`.  Great to know that `FetchXML` is an option if needed.
