### ISSUE TITLE
Two CRM tables that our `applicants` will be sent to / retrieved

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicant-portal#115]
Just flagging that we're going to need to (at some point) specify the two CRM tables that our `applicants` will be sent to / retrieved from.  

_Think_ the name of the other applicant array is: `dcp_dcp_applicantrepinformation_dcp_pasform` but gotta double check that.

_Originally posted by @bfreeds in https://github.com/NYCPlanning/labs-applicant-portal/pull/113_

**Comment by hannahkates** [comment]
is this still relevant @allthesignals ? if so, can you label and place it in a pipeline accordingly?

**Comment by hannahkates** [comment]
Aren't we doing this already? I don't understand this issue.

**Comment by allthesignals** [comment]
I think it's closed @bfreeds original comment

**Comment by bfreeds** [comment]
Yep - closed with #260
