### ISSUE TITLE
Skeleton form for new project

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/labs-applicant-portal#1245]
## Acceptance Criteria
- [x] Feature is behind feature flag from #1242
- [x] Create page for new project form
- [x] Create a skeleton form
- [x] Place a single placeholder field within the form
- [x] A validator should check whether the placeholder field is filled out
- [x] When the placeholder field is filled out, users can hit the 'submit' button

## Depends on:
#1242 

## Product Epic
- Features 
   - 2, Create an online form
- Story
   - 7, Allow users to submit form

**Comment by TangoYankee** [comment]
@horatiorosa , I'm thinking we create a `project-new` model, rather than trying to reuse other project models

**Comment by Eabrante** [comment]
@horatiorosa @TangoYankee I removed the City Wide option from the borough option set. Applicants will not be able select City wide from the portal form. https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/17792
