### ISSUE TITLE
Submit project details for new project

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/labs-applicant-portal#1249]
# Description
Add details for the project to the project form, to include project validation

## Acceptance criteria
- [x] Is behind Feature Flag #1242
- [x] The "New Project" form contains the fields associated with project information
- [x] Fields have validators that must pass before the "submit" button is enabled
- [x] Pressing "submit" sends form to the API endpoint #1246 

## Depends on
#1246 

### Product Epic
- Features:
   - 2, Create form [AB#17788](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/17788)
- Stories
  - 3, New project request [AB#17792](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/17792)

**Comment by Eabrante** [comment]
@horatiorosa @TangoYankee I removed the City Wide option from the borough option set. Applicants will not be able select City wide from the portal form. https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/17792
