### ISSUE TITLE
Help blurb is missing on "my projects" page

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#128]
## What should happen:
The "my projects" page should have this help message in the top right.
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/81cd4c5c-5e96-4b2b-bf14-66fbf2bdf470)

## What happened instead:
It used to be there, but it disappeared.

On develop:
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/ac6c52db-886c-4cc5-aa18-381d0f9f3046)

**Comment by andycochran** [comment]
Looks like this was accidentally nixed here: https://github.com/NYCPlanning/labs-applicant-portal/commit/e5aa4c3ddd10456e5ade6f2d467caf4d7700bc7b#diff-5fa8248f953a4688f18d7ecefd989a69L41-L47
