### ISSUE TITLE
Setup NYC.ID auth

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#13]
1. Get account creds/account
2. Use oauth

We'll need it set up for multiple environments, including prod, staging, QA, and dev.

Se if we can set up more seats for this.

**Comment by allthesignals** [comment]
I'm going to investigate if we can use existing accounts

**Comment by allthesignals** [comment]
We can use existing accounts to set up new service accounts for new apps.
