### ISSUE TITLE
Mystery number instead of revision number

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#134]
The edit PAS package button is supposed to display the package revision number (example: Revision 2). Instead, it's displaying a mysterious number. Example in screenshot.

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/e55dcaad-de2a-442e-9b19-5a8f34084090)

**Comment by allthesignals** [comment]
Hmm... I'm using the `versionnumber` here. 

I think it needs to be the `dcp_packageversion`! Will PR...

**Comment by allthesignals** [comment]
https://github.com/NYCPlanning/labs-applicant-portal/pull/145
