### ISSUE TITLE
Query for an applicants' active projects

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#15]
AB#10519

## User story
As an applicant team member, I need to see all of my active projects and see which ones I can take action on (i.e. submit a PAS).

**This requires linking the following entities with filters applied along the way:**
dcp_projectapplicant --> dcp_project --> project packages (we only want PAS)

## Attributes
**For each project in the response, we need the following attributes:**
- [ ] project name (source: dcp_project field: `dcp_projectname`)
- [ ] project id (source: dcp_project field: `dcp_name`)
- [ ] primary applicant (source: dcp_project field: `dcp_name`)
- [ ] PAS package ID (field: ?)
- [ ] PAS package status (field: `statuscode`)

## Filters to apply
**Filter 1:** We only want projects that are active and visible:
**dcp_projectapplicant**:
`contact = contactid` (obtained from contact table using user's email)
`AND statuscode = 'Active'`
**dcp_project:** (joined using projectid from dcp_projectapplicant)
`statecode = 'Active'`
`AND dcp_visibility IN ('Applicant Only', 'General Public')`

**Filter 2:** We only want PAS package info joined onto the project if the PAS package has been made visible:
`dcp_visibility IN ('Applicant Only', 'General Public')`

## [Figma Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP-Wireframes?node-id=0%3A1)
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/c6451185-5af5-4c10-909f-32e50347cb4f)

**Comment by allthesignals** [comment]
Research issue: https://github.com/NYCPlanning/labs-applicant-portal/issues/2

**Comment by allthesignals** [comment]
```
dcp_projects?$filter=dcp_dcp_project_dcp_projectapplicant_Project/any(o:o/
_dcp_applicant_customer_value eq  'A42C6343-455A-EA11-A9A8-001DD8308047')
&$expand=dcp_dcp_project_dcp_package_project(
   $filter=statecode eq 0),
 dcp_dcp_project_dcp_projectapplicant_Project(
   $filter=statecode eq 0)
```

**Comment by allthesignals** [comment]
Some questions:
 - How do we handle revisions?
 - How do revisions appear in the CRM data model?
 - Can there only be one PAS Form because there can only be one package of each type?

**Comment by hannahkates** [comment]
@allthesignals Users should only see active, unsubmitted PAS packages OR the most recent inactive submitted ones. They should not see the older inactive revisions. If there are multiple revisions, we should display the revision number. 

This issue captures that Aline's comments - I didn't think to grab it for this sprint, since I was thinking of it as more of the 2nd part of the MVP (submission), but you're right, it's relevant now for the query. https://app.zenhub.com/workspaces/labs-sprint-5e56ebd113bedb2575e694da/issues/nycplanning/labs-applicant-portal/29

**Comment by allthesignals** [comment]
@hannahkates okay, I think that makes sense. 

> **If there are multiple revisions, we should display the revision number.**

Okay! 

@hannahkates  Can we get on screenshare at some point today and build out some sample applications in UAT2?

**Comment by allthesignals** [comment]
- [ ] Make sure we have packages of all types setup in UAT2 for testing... make this a script!

**Comment by andycochran** [comment]
Updated the wireframes to indicate the revision (if it's not the first version): 

![image.png](https://images.zenhubusercontent.com/5ca23880d9fcf5278d71596e/dcd7a46a-026f-4f7c-8789-bfdbd1d6f605)
