### ISSUE TITLE
View page needs to list actual data (+brainstorm refactor)

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#161]
## What should happen:
The view-only page after PAS submission should display all the data you user just submitted

## What happened instead:
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/12f4e3e4-1b29-46fd-a0f5-d478f34cec76)

**Comment by bfreeds** [comment]
Quick fix to show real data has been merged into `develop` and is in an open PR to be brought into `qa` for testing.  

Next steps will be to refine the styling and refactor for code maintainability, however once that PR is brought into QA this will not be blocking testing.
