### ISSUE TITLE
Applicant team members aren't displaying in CRM

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#162]
## What should happen:
When the user saves the form, the applicant team info they saved should get sent to Dynamics CRM.

## What happened instead:
The tables on Dynamics CRM PAS form page doesn't get filled in, even though the data has been successfully sent to CRM and can be retrieved by the front-end app.
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/deb546ba-cec4-47f9-8d54-c3ce19ce97ec)

## How to reproduce this bug:

1. Edit a PAS form by adding applicant team data
2. Save the form changes
3. View that PAS form in Dynamics CRM and see that the applicant tables are both blank.

**Comment by allthesignals** [comment]
Here's some validation information we received from @Eabrante 

| field | Label | Required | Type | Validation | Default | Notes |
|------------------|--------------|----------|------------|------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| dcp_organization | Organization | Yes | Text | Length: 100 | Blank | If 'Type' field value is selected as “Authorized Applicant Representative” then show below field on the form else hide it from form: Organization |
| dcp_name | Full Name | Yes | Read-only |  |  |  |
| dcp_firstname | First Name | Yes | Text | Length: 50 | Blank |  |
| dcp_lastname | Last Name | Yes | Text | Length: 50 | Blank |  |
| dcp_type | Type | Yes | Option Set | 1. Applicant  2. Authorized Applicant Representative | Null | From MCS Portal - Get all Applicant Information associated to current PAS Form where Type Optionset value = Applicant or Authorized Applicant Representative and Applicant Information.status = Active |
| emailaddress1 | Email | Yes | Text |  | Blank |  |
| dcp_address | Address | Yes | Text | Length: 250 | Blank |  |
| dcp_city | City | Yes | Text | Length: 80 | Blank |  |
| territorycode | State | No | Option Set | Value: US States | Null |  |
| dcp_zipcode | Zip Code | No | Numeric | Length: 5 | Blank |  |
| telephone1 | Phone | No | Numeric | Length: 10 | Blank |  |

![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/5cdb99e6-1f13-4033-90b9-009a476a67d4)

**Comment by bfreeds** [comment]
Interesting, in UAT2 environment, using the CRM power selector tool, these are the database fields that appear for this table:
![image](https://user-images.githubusercontent.com/5316367/81309599-1ce8f000-9051-11ea-9425-7dbafae18ff3.png)
Differences are:
- `dcp_email` vs. `emailaddress1`
- `dcp_state` vs. `territorycode`
- `dcp_phone` vs. `telephone1`

**Comment by bfreeds** [comment]
When adding an applicant to either of these tables in CRM, it's a lookup, I'm not clear what it's looking up _to_
![2020-05-07 11 03 22](https://user-images.githubusercontent.com/5316367/81310693-6dad1880-9052-11ea-92f4-104f699c6413.gif)

**Comment by Eabrante** [comment]
@bfreeds You are correct. I'm updating this document now on my desktop with information shared from Bujji. I will reshare shortly.

**Comment by allthesignals** [comment]
Ready to test :)

**Comment by ksinghprod** [comment]
This issue is fixed @Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82375274-5412b600-99ee-11ea-8178-6113054e56c4.png)

![image](https://user-images.githubusercontent.com/57362229/82375429-950aca80-99ee-11ea-9743-d87e9b032466.png)
