### ISSUE TITLE
Make uploaded files available on PAS form

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#167]
[Azure Requirement](#)

### User Story
As a {type of user}, I want {some goal} so that {some reason}
### User Journey
Capture the experience of interacting with a specific feature. This should capture any conditional experiences depending on actions the user takes.

### [Wireframes](#)
Provide link to Figma
Paste in screenshots

**** add icon that shows file will open in new tab

### Display Logic
Captures specifics about the data and how attributes of the data should determine a record’s styling or where a record gets displayed on the page.

### Attributes
What attributes should the API response include?
### Filter Logic
Which records should be included? Which should be excluded?

## Unresolved Questions

**Comment by allthesignals** [comment]
Two paths I can think of: 

 - Generate special read-only cookie for user to be able to click the file links natively 
 - Funnel the file through our authenticated API to the user

 - ???

**Comment by godfreyyeung** [comment]
Things required for funneling file through our API:

a. A backend endpoint to deliver a file (Binary content) for given file
  - Endpoint will hit the sharepoint API, download the file to server memory, and include it in the response to the frontend.
b Frontend action on each file link to generate the proper parameters and hit the endpoint in A.
c. Possibly some other frontend work to handle a buffer and hand it off to the buffer? Initiate a download? <-- not sure if this is possible.
