### ISSUE TITLE
Prevent route changes if attributes are dirty

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#169]
[Azure Requirement](#)

### User Story
As a {type of user}, I want {some goal} so that {some reason}
### User Journey
Capture the experience of interacting with a specific feature. This should capture any conditional experiences depending on actions the user takes.

### [Wireframes](#)
Provide link to Figma
Paste in screenshots

### Display Logic
Captures specifics about the data and how attributes of the data should determine a record’s styling or where a record gets displayed on the page.

### Attributes
What attributes should the API response include?
### Filter Logic
Which records should be included? Which should be excluded?

## How to reproduce this bug:

1. Step one
2. ???
3. Error

**Comment by bfreeds** [comment]
Closing, encompassed by #27
