### ISSUE TITLE
Create "My Projects" user dashboard

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#17]
AB#10519

## User Story:
As an applicant team member, I need to see all of my active projects and see which ones I can take action on (i.e. submit a PAS).

## Display Logic:

**Project shows up in the left "To DO" column with an "Edit Pre-Application Statement" button if**
PAS package `statuscode IN ('Saved', 'Package Preparation')`

**Project shows up in the right "Working on it..." column with a "View Pre-Application Statement" button if**
PAS package `statuscode IN ('Submitted', 'Under Review', 'Revision Required')`
^ all statuses except for 'Mistake'

**Project shows up in the right "Working on it..." column with no button if** 
Project is missing PAS data because the PAS package isn't visible or hasn't been created yet

**If user isn't assigned to any projects**
Page should display “You are not currently assigned to a DCP project. Please email ZAP_Feedback_DL@planning.nyc.gov for further assistance.” 

## [Figma Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP-Wireframes?node-id=0%3A1)
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/33a6f149-e556-410a-97a4-7dd84e45e534)

**Comment by bfreeds** [comment]
@hannahkates @andycochran
