### ISSUE TITLE
Install and configure New Relic for Application Performance Monitoring

### ISSUE THREAD

**Issue by bfreeds** [NYCPlanning/labs-applicant-portal#170]
### User Story
As an application developer, I want to have auditable clear and robust monitoring and error handling so that I can diagnose application problems and improve user experience.
### User Journey
I want a centralized place to see application errors and performance (time for queries, network request, etc).

### Attributes
Install New Relic on the nest.js api server.  We want:
- Application Logging (activity, requests, etc.)
- Performance Logging
- Error Logging

## Unresolved Questions
- What limitations do we have on the free tier of New Relic APM?

**Comment by bfreeds** [comment]
Holding off on this for maintenance sprint and alongside auditing Heroku resources before adding another one.

**Comment by hannahkates** [comment]
Related to #526

**Comment by godfreyyeung** [comment]
Alternatives:
- AppDynamics
Logging centric:
- Pino
- 0gma
- Winston

Log experience:
- PaperTrail
- Corologix
- LogDNA

**Comment by godfreyyeung** [comment]
Checklist
- [x] Logging
- [ ] Performance monitoring
