### ISSUE TITLE
Submit isn’t disabled while form is dirty

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicant-portal#172]
[Azure Requirement](#)

### User Story
As an applicant, I want to feel confident that I'm not submitting an incomplete form.

### User Journey
Capture the experience of interacting with a specific feature. This should capture any conditional experiences depending on actions the user takes.

## What should happen:
Submit isn’t disabled while form is dirty

## What happened instead:
Submit button is always clickable

**Comment by bfreeds** [comment]
Closing as this is encompassed by #27
