### ISSUE TITLE
Initial applicants state triggers "dirty" state, shows clickable Save button

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicant-portal#173]
[Azure Requirement](#)

## What should happen:
Save button becomes clickable on first form load (it shouldn't) 

## What happened instead:
Save Button begins by being active if the initial pas form has an empty array of applicants (because we then implicitly create a new applicant).

**Comment by allthesignals** [comment]
Unsure of best way to deal with this. Creating a record in the store puts it in a dirty state, and that's what the applicants component does implicitly. 

Might require a refactor of how that component deals with initial state.

**Comment by godfreyyeung** [comment]
I thought per our recent Teams discussion, we have consensus this is okay?

**Comment by hannahkates** [comment]
Yeah I don't think there's anything wrong with being able to save nothing. Closing.
