### ISSUE TITLE
Implement front-end validations

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#174]
On save:
- [ ] Field character limits (see wireframes)

On submit:
- [ ] Need at least one file to upload
- [ ] Conditionally required fields
- [ ] Need to have at least one applicant and the "type" of that applicant

**Comment by trbmcginnis** [comment]
Connecting to the "Submit" issue so we can make sure we know which button (**Save** vs **Submit**) has which validations.

https://app.zenhub.com/workspaces/labs-sprint-5e56ebd113bedb2575e694da/issues/nycplanning/labs-applicant-portal/27

**Comment by hannahkates** [comment]
@godfreyyeung this is also related to #162. The user needs to specify the type of applicant they add.
