### ISSUE TITLE
In confirm PreApplicant statement submission message Pop up, horizontal scroll bar is displayed at the bottom

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#180]
Browser: Chrome, Firebox, IE

Actual Result: In Applicant Portal, PAS form, upon clicking submit in CONFIRM PRE-APPLICANT STATEMENT SUBMISSION message pop up, a horizontal scroll bar is displayed.

Expected: bottom scroll bar should not be displayed unless there is hidden text that requires scrolling.

URL: https://qa.applicant-portal.planninglabs.nyc/packages/a44a78ad-1a8b-ea11-a815-001dd8309530/edit

![image](https://user-images.githubusercontent.com/63460627/81208506-287adf00-8f9d-11ea-9cd7-f1732b38db6f.png)

**Comment by hannahkates** [comment]
I think this is only Sev4. It's UI related and doesn't impact the user's ability to submit.

**Comment by ksinghprod** [comment]
This issue is fixed
@Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82255502-c0c07e80-9922-11ea-89e4-d1ca9a0956f3.png)
