### ISSUE TITLE
The geographic State (NY, etc) entered by the applicant disappears after saving the PAS Form 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#183]
## Browser(s) and Device(s) observed on: 
Chrome, Firefox, IE

## What should happen:
The state entered in the state field by the applicant, should be saved when the applicant clicks on the save button on the PAS form

## What happened instead:

The state entered by the applicant disappears after saving the PAS Form 

## How to reproduce this bug:

1. Log Into Applicant Portal
2. Click on the Edit Pre-Application Statement button
3. Navigate to the Applicant team 
4. Fill out all fields for the applicant team member, including State
5. Click on the Save button (error happens here)

## ADO Test Case
 R10744-AC1-1, step 5 
https://dcp-paperless.visualstudio.com/ZAP%20Portals/_testPlans/define?view=_TestManagement&planId=10799&suiteId=10912

![image](https://user-images.githubusercontent.com/57362229/81218385-1e141180-8fac-11ea-923e-5a680a18c9f9.png)

![image](https://user-images.githubusercontent.com/57362229/81301750-73e9c780-9047-11ea-90c3-06509a44e807.png)

**Comment by hannahkates** [comment]
The cause of this is #210. We had thought it was text, not an option set.

**Comment by godfreyyeung** [comment]
I'm going to look at this

**Comment by ksinghprod** [comment]
This issue is now fixed 
@Hemachekuri 
![image](https://user-images.githubusercontent.com/57362229/82242910-aaa7c380-990c-11ea-9bf4-0f23c7140c0f.png)
