### ISSUE TITLE
Select "Individual" as default type for applicant

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#184]
## Browser(s) and Device(s) observed on:
Chrome, Firefox, IE

## What should happen:
 Either applicant radio button should be selected by default and user can later select organization,

## What happened instead:
In applicant section, by default the team member defaults to applicant but the radio button is not selected

## How to reproduce this bug:
Log Into Applicant Portal
Click on the Edit Pre-Application Statement button
Navigate to the Applicant team
do not select individual or organization radio button
Fill out all fields for the applicant team member
Click on the Save button 
applicant is able to save without selecting Individual or organization radio button
Chrome

![image](https://user-images.githubusercontent.com/63460627/81219316-a5ae5000-8fad-11ea-95ad-5e6a4cc57265.png)

**Comment by hannahkates** [comment]
@Hemachekuri I think this is Sev4. I agree it could be confusing, but this data isn't actually stored in the CRM database. It doesn't negatively impact anything in the system if the user doesn't select one or the other.

@bean75 What's your opinion on whether we should default to choosing Applicant for the user vs. leaving it blank so they are forced to intentionally chose one or the other?

**Comment by bean75** [comment]
I am a bit confused. Is the bug that there is no default radio button selected for individual vs org? I thought in CRM there is no null option - one has to be selected. Is that the reason this is a bug? Or is it something else?

**Comment by hannahkates** [comment]
@Hemachekuri can you clarify? 

I think we should keep this github issue focused on the UI question of whether to select a default option for the user. 

We can include the validation for the required applicant "type" value in issue #162 and #174.

**Comment by ksinghprod** [comment]
Hi @hannahkates , 

When the User navigates to the Applicant team Tab and enters applicant info, by default the form/system displays the fields for the individual applicant (which makes sense). However, the Individual's radio button is not selected by default

cc @Hemachekuri

**Comment by hannahkates** [comment]
Okay I'm updating the title of the issue to make it clearer and moving it to "to do". We will make the radio button default to select "Individual"

**Comment by ksinghprod** [comment]
This issue is now fixed 

cc: @Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/81832753-df7ed980-950c-11ea-9f1d-feecb9589553.png)
