### ISSUE TITLE
when applicant changes Project Name and save in the PAS form, it is not reflect in respective Project in my projects in the main applicant portal Projects display of the user

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#185]
## What should happen:
when applicant changes Project Name and save in the PAS form, it should reflect in respective Project in my projects in the main applicant portal Projects display of the user
## What happened instead:
when applicant changes Project Name and save in the PAS form, it is not reflect in respective Project in my projects in the main applicant portal Projects display of the user
## How to reproduce this bug:

1. Log in and click on the Edit Pre application statement of the project.
2. Rename the Project name and save
3. log out and log in and verify the Project name of the respective project.
4. when applicant changes Project Name and save in the PAS form, it is not reflect in respective Project in my projects in the main applicant portal Projects display of the user

## Browser(s) and Device(s) observed on:
![image](https://user-images.githubusercontent.com/63460627/81222215-ee680800-8fb1-11ea-9508-6ed4ac42f624.png)

![image](https://user-images.githubusercontent.com/63460627/81222046-aea12080-8fb1-11ea-8fa9-fd913a88860f.png)

**Comment by hannahkates** [comment]
@Hemachekuri This is expected behavior. The project name should only be overwritten upon submitting the PAS form, not saving.
