### ISSUE TITLE
Once the documents are uploaded, Document name is displayed but  "added with date" is not displayed.

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#186]
Browser: IE and Chrome

What should happen:
Once the documents are uploaded, Document name is displayed but  "added with date" should be displayed.
What happened instead:
Once the documents are uploaded, Document name is displayed but  "added with date" is not displayed instead to be added is displayed

User story: 10748 AC3 or 4
https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/10927
Step: 17

![image](https://user-images.githubusercontent.com/63460627/81223178-992cf600-8fb3-11ea-9f6c-fb93bbfdfbfc.png)

![image](https://user-images.githubusercontent.com/63460627/81223234-aea22000-8fb3-11ea-9a5a-31c05d86ac13.png)

**Comment by hannahkates** [comment]
@Hemachekuri The date shouldn't show up until the file has actually been saved to Dynamics CRM. In the screenshot you've shared, the file hasn't been saved yet, so it displays "TO BE ADDED" instead.

I realize you can't save right now because of issue #187, so that makes it harder to see the full user journey for this. Let's this issue open to re-evaluate once #187 is fixed.

**Comment by Hemachekuri** [comment]
Date is not displayed. Hence reopened.
![image](https://user-images.githubusercontent.com/63460627/81986466-d9205880-9605-11ea-801a-dc0f32653a16.png)

**Comment by hannahkates** [comment]
I'm seeing this too. Once you refresh the page, the file completely disappears. I think it's not saving the file to CRM/Sharepoint correctly. Moving this back to "to do"

**Comment by allthesignals** [comment]
I think this should be fine now, it's showing the dates for uploaded files.

A weird UX issue, though, is after a file is uploaded successfully, it disappears from the list until you do a hard refresh. @godfreyyeung have you noticed this?

**Comment by hannahkates** [comment]
This is resolved. The refresh issue is documented in #290 and @229.

**Comment by ksinghprod** [comment]
This issue is fixed, 
@Hemachekuri 
![image](https://user-images.githubusercontent.com/57362229/82333769-252c1e00-99b5-11ea-9998-ca20325ebe32.png)
