### ISSUE TITLE
When a user edits the PAS form by only uploading a document, the save button is still disabled 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#187]
## Browser(s) and Device(s) observed on:
Chrome, Firefox, IE

## What should happen: 
Save button should be enabled after the applicant has made a chance to the PAS Form, including solely uploading a document 

## What happened instead: 
When a user uploads a document, the save button is still disabled (no other edits were made

## How to reproduce this bug:
1. Log Into Applicant Portal
2. Click on the Edit Pre-Application Statement button
3. Make any edits to the PAS form
4. Click on the Save button, after saving make sure the save button is disabled
5. Navigate to the Attached Documents Section and upload a document (error happens here)

## ADO Test Case: 
R10524-AC3-2, step 13 

https://dcp-paperless.visualstudio.com/ZAP%20Portals/_testPlans/define?view=_TestManagement&planId=10799&suiteId=10903

![image](https://user-images.githubusercontent.com/57362229/81223425-f5901580-8fb3-11ea-957f-8c631dcb8695.png)

**Comment by Hemachekuri** [comment]
Hannah,
I added the document, now the save button is enabled for saving, and upon clicking on save, it is not saving and save button is still enabled.
![image](https://user-images.githubusercontent.com/63460627/81330170-b58d6900-906d-11ea-8582-4bd097327cd1.png)

**Comment by Hemachekuri** [comment]
and upon refresh, save button is disabled and uploaded doc is not displayed, so in document section, save is not working

**Comment by Hemachekuri** [comment]
![image](https://user-images.githubusercontent.com/63460627/81330531-36e4fb80-906e-11ea-97ee-ae58ee1184d1.png)

**Comment by ksinghprod** [comment]
This Issue is now fixed 
@hannahkates @Hemachekuri 
![image](https://user-images.githubusercontent.com/57362229/82093075-69bf6d00-96c8-11ea-992f-6cf9871e4f1d.png)
