### ISSUE TITLE
Create view only PAS form page

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#19]
## User Story
As an applicant, I want to be able to view the PAS form that I already submitted so I can have a record of what info I provided.

## [Figma Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP-Wireframes?node-id=0%3A1)
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/9cfa328a-18ff-4cf3-a091-125d3f667f89)

**Comment by allthesignals** [comment]
Route structure:

view: project-applicant-statements/:id
edit/new: project-applicant-statements/:id/edit

We should keep it all in one component. But does view/edit/new states all go in the same component? Maybe we can have a state for that.
