### ISSUE TITLE
The Applicant is able to change the length of the Text Box for Certain fields 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#194]
## Browser(s) and Device(s) observed on:
Chrome, Firefox, IE
## What should happen:
User should only be able to enter the text in the fields of the PAS form, should not be able to change the text box size by dragging 

## What happened instead:
For the following fields the user is able to drag and change size of the text box: 
Description of geography  
Description of the proposed development being facilitated by the land use actions
Why is this application being proposed? What is the legal, environmental, or land use background?
What is the land use rationale for all the proposed actions?
Description of existing land uses and structures in the proposed Project Area and Development Site
Description of land uses and built context in surrounding area (within 1000 ft)
Description of proposed CEQR scope
## How to reproduce this bug:

1. Log in to Applicant Portal
2. Click on the Edit Pre-Application Statement Button
3. Navigate to the following fields and drag the field's answer text  box to resize: Description of geography  
Description of the proposed development being facilitated by the land use actions
Why is this application being proposed? What is the legal, environmental, or land use background?
What is the land use rationale for all the proposed actions?
Description of existing land uses and structures in the proposed Project Area and Development Site
Description of land uses and built context in surrounding area (within 1000 ft)
Description of proposed CEQR scope

![image](https://user-images.githubusercontent.com/57362229/81323948-36dffe00-9064-11ea-9898-bc3d845c2fc8.png)

**Comment by hannahkates** [comment]
Shouldn't this be Sev4? This is a purely visual issue. The user can still enter the same amount of text up to the maximum character limit, regardless of the size of the box.

**Comment by ksinghprod** [comment]
Sure Hannah, changing severity to 4.

**Comment by andycochran** [comment]
I think this bug should be close as won't fix. It is the intended/default behavior that users can resize a `<textarea>` element. This does not affect how many characters can be entered into the element. 

Aside: In a future iteration, we might explore auto-sizing text boxes that grow/shrink to fit the entered content (with a min and max height), but that also isn't an MVP requirement. 

However, I will look into preventing the user from adjusting the width of the text boxes.

**Comment by ksinghprod** [comment]
this issue is not fixed 
@Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82255624-f9605800-9922-11ea-9aec-4746518438d9.png)

![image](https://user-images.githubusercontent.com/57362229/82255663-0bda9180-9923-11ea-94dc-da7f0b2d18d4.png)

**Comment by hannahkates** [comment]
Based on Andy's comment above, we are not considering this a bug. Andy made a fix so that users can't adjust the width of the box. Allowing them to adjust the height is actually a benefit because it allows them to see the entirety of what they have typed. We should close this issue. If users complain, we will adjust accordingly.

**Comment by ksinghprod** [comment]
Sure Hannah, closing this issue as per Hannah's and Andy's comments
