### ISSUE TITLE
The Package Status Date Is not visible to the Applicant 

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#195]
[AB#11029](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/11029)

## Browser(s) 
IE Browser and chrome

## What should happen:
User should be able to see the Package Status Date on the Applicant portal as part of the Package Details 

## What happened instead:
Applicant is not able to see the package status date for the PAS Package/Form 

## How to reproduce this bug:
1. Log Into Applicant Portal
2. Navigate to the a project has as an Edit Pre-Application Statement Button 
3. Verify that the following Details are present:
Package Name
Package Type
Package Version
Package Status 
Package Status Date [Package Status date is not visible]

## ADO Test Case: 

R10524-AC2-1, Step 12
https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/10869

![image](https://user-images.githubusercontent.com/57362229/81328860-98579b00-906b-11ea-8c3f-f4b1bc7b3bec.png)

![image](https://user-images.githubusercontent.com/57362229/81329096-043a0380-906c-11ea-88c6-97e0e7dc8455.png)

**Comment by hannahkates** [comment]
@bean75 Do you think it's essential for MVP for the applicant to see the date a package status was last updated?

**Comment by bean75** [comment]
It lets them know when it is made available to them or when the review was completed.
Since we aren't displaying the milestones, I think it makes sense - is there some other way you were thinking of conveying time in hand?
________________________________

**Comment by hannahkates** [comment]
No, we didn't have any plans for showing dates at this point. When we do the RWCSD build, we will also need to create the project page that lists all the packages. That project page feels like a better place to store dates related to the packages. Would it be okay to wait for that, rather than add more data to this temporary "my projects" design?

CC @andycochran who's starting to think about design for the project page

**Comment by bean75** [comment]
Thank makes sense.
________________________________

**Comment by hannahkates** [comment]
Ok thanks. @Hemachekuri I'm marking this issue as resolved since we will provide package dates in a better format on the project page during the RWCDS build.

**Comment by ksinghprod** [comment]
This will be revisited, retested in a future sprint @Hemachekuri

**Comment by allthesignals** [comment]
To be addressed by https://github.com/NYCPlanning/labs-applicant-portal/issues/378

**Comment by ksinghprod** [comment]
This issue is now fixed 
cc @B-o-s-s-e-s 

![image](https://user-images.githubusercontent.com/57362229/90541377-87312680-e150-11ea-975d-bb242554297e.png)
