### ISSUE TITLE
In Proposed Land Use Actions in zoning Text amendment, in How many Zoning Text amendment actions, user is able to add negative values

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#197]
Browser(s) IE Browser and chrome

What should happen:
In Proposed Land Use Actions in zoning Text amendment, in How many Zoning Text amendment actions, user should not be able to add negative values
What happened instead:
In Proposed Land Use Actions in zoning Text amendment, in How many Zoning Text amendment actions, user is able to add negative values
How to reproduce this bug:
Log Into Applicant Portal
Click on the Edit Pre-Application Statement button
Navigate to the Proposed Land Use action, and select any item like change in city map.
How many changes in City map is displayed with input text box, and in that input box, In Proposed Land Use Actions in zoning Text amendment, in How many Zoning Text amendment actions, user should not be able to add negative values

Click on the Save button (error happens here)

![image](https://user-images.githubusercontent.com/63460627/81325127-ecf81780-9065-11ea-89c1-78154356da00.png)

![image](https://user-images.githubusercontent.com/63460627/81324904-a3a7c800-9065-11ea-8c2d-a9163d6c39d9.png)

**Comment by hannahkates** [comment]
The Dynamics CRM system allows negative numbers, but we can discourage users from submitting them in the front-end app. @godfreyyeung could this be included in #174?

**Comment by hannahkates** [comment]
This should be considered with #245

**Comment by trbmcginnis** [comment]
We could add a validation for `save` where users are unable to save if this value is below 1. Only relevant for "Zoning Certification", "Zoning Special Permit", and "Zoning Authorization".

**Comment by Hemachekuri** [comment]
Working good. Hence closed
![image](https://user-images.githubusercontent.com/63460627/82350988-008e7100-99ca-11ea-8cea-e484d1a5ff73.png)
