### ISSUE TITLE
In Project area section, when user selects and saves, input values are disappearing.

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#198]
Browser(s) IE Browser and chrome

What should happen:
In Project area section, after the use selects all the items radio buttons and saves,  values should be saved.
What happened instead:
In Project area section, after the use selects all the items radio buttons and saves,  few fields are saved and few fields are not saved and radio button value is disappearing
How to reproduce this bug:
Log Into Applicant Portal
Click on the Edit Pre-Application Statement button.
Navigate to Project area section.
In Project area section, after the use selects all the items radio buttons and saves,  yellow highlighted feilds, then upon save selection radio button value is disappearing
![image](https://user-images.githubusercontent.com/63460627/81326034-2e3cf700-9067-11ea-96f4-ab232f1b38d9.png)
![image](https://user-images.githubusercontent.com/63460627/81326081-41e85d80-9067-11ea-9957-6cf2c2df89b1.png)

**Comment by hannahkates** [comment]
This is a known issue we are currently working on in #163.

**Comment by ksinghprod** [comment]
This Issue is now fixed

![image](https://user-images.githubusercontent.com/57362229/81980510-c2c1cf00-95fc-11ea-91db-b01870eda089.png)
