### ISSUE TITLE
In Proposed development site section, and select all radio buttons as yes and input values in text boxes and save, all the input values are not getting saved.

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#199]
## Browser(s) 
IE Browser and chrome

## What should happen:
In Proposed development site section, and select all radio buttons as yes and input values in text boxes and save, all the input feilds should be saved.
In what year do you expect the development to complete? - In put value should be displayed
Does the proposed development involve discretionary funding for Affordable Housing Units? selected radio button of Yes has is not displayed and hence funding source field should be displayed.

What happened instead:
In Proposed development site section, and select all radio buttons as yes and input values in text boxes.
In what year do you expect the development to complete? - In put value is not displayed
Does the proposed development involve discretionary funding for Affordable Housing Units? selected radio button of Yes has is not displayed and hence funding source field is not displayed.
How to reproduce this bug:
Log Into Applicant Portal
Click on the Edit Pre-Application Statement button
Navigate to In Proposed development site section, and select all radio buttons as yes and input values in text boxes.
In what year do you expect the development to complete? - In put value is not displayed
Does the proposed development involve discretionary funding for Affordable Housing Units? selected radio button of Yes has is not displayed and hence funding source field is not displayed.
 
 
![image](https://user-images.githubusercontent.com/63460627/81328533-17989f00-906b-11ea-89a6-09bb2fa06eb4.png)
![image](https://user-images.githubusercontent.com/63460627/81328564-1ff0da00-906b-11ea-82b9-1e29e9d8b01b.png)

Upon save:
![image](https://user-images.githubusercontent.com/63460627/81328597-2da65f80-906b-11ea-9c86-4fac1103d6f1.png)
![image](https://user-images.githubusercontent.com/63460627/81328617-35fe9a80-906b-11ea-8e1f-c64c90a8dbcf.png)

**Comment by hannahkates** [comment]
This seems like an example of #163.

**Comment by ksinghprod** [comment]
This issue is not fixed, "In what year do you expect the development to complete?" field's answer does not save
![image](https://user-images.githubusercontent.com/57362229/81981343-2d273f00-95fe-11ea-9a08-9049ba6a8a85.png)


after saving


![image](https://user-images.githubusercontent.com/57362229/81981406-416b3c00-95fe-11ea-8778-c29e30006c16.png)

**Comment by hannahkates** [comment]
Ok, we have that year captured in #215. Glad that's the only one left to fix!

**Comment by ksinghprod** [comment]
This issue is not fixed 
will be fixed, when issue #215 is resolved 

![image](https://user-images.githubusercontent.com/57362229/82092750-db4aeb80-96c7-11ea-88e2-fcca40d7c5a0.png)

**Comment by ksinghprod** [comment]
This issue is fixed 

@Hemachekuri 
![image](https://user-images.githubusercontent.com/57362229/82259212-30396c80-9929-11ea-99dc-f167b4594921.png)
