### ISSUE TITLE
Create JSON API query that obtains a contact's projects and PAS statuses

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#2]
Starting with a user's contact ID, try to create the following chained, joined query

- Query the dcp_projectapplicant table to get the contact's assigned project IDs
- From dcp_project table, get project visibility and statuscode=active
- Get the associated PAS packages
- Get the status and visibility of the PAS packages

contact -> projectapplicantteam -> project -> paspackage

Final query: 

```
https://dcppfsuat2.crm9.dynamics.com/api/data/v9.1/dcp_projects?$filter=dcp_dcp_project_dcp_projectapplicant_Project/any(o:o/_dcp_applicant_customer_value eq  'A42C6343-455A-EA11-A9A8-001DD8308047')&$expand=dcp_dcp_project_dcp_package_project($filter=statecode eq 0),dcp_dcp_project_dcp_projectapplicant_Project($filter=statecode eq 0)
```

**Comment by allthesignals** [comment]
This is a query that obtains a contact's projects: 

https://dcppfsuat2.crm9.dynamics.com/api/data/v9.1/dcp_projectapplicants?$filter=_dcp_applicant_customer_value%20eq%20%27A42C6343-455A-EA11-A9A8-001DD8308047%27&$expand=dcp_Project

**Comment by allthesignals** [comment]
https://dcppfsuat2.crm9.dynamics.com/api/data/v9.1/dcp_projectapplicants?$filter=_dcp_applicant_customer_value%20eq%20%27A42C6343-455A-EA11-A9A8-001DD8308047%27&$expand=dcp_Project,dcp_projectapplicant_dcp_package_applicant

This tries to expand something that _looks_ like the associated packages, but I can't seem to get it to include what I normally see on the MS applicant portal.

**Comment by allthesignals** [comment]
Here's an example of a PAS Form endpoint: https://dcppfsuat2.crm9.dynamics.com/api/data/v9.1/dcp_pasforms(eeeed605-1ce8-e811-8149-1458d04dc8c8)?$expand=dcp_projectname

**Comment by allthesignals** [comment]
I'm a big stuck getting the right packages in an economical way (using 1 query and avoid an N+1 situation). I am reaching out to some folks who would have a better idea of using this web API.

**Comment by allthesignals** [comment]
I just e-mailed Aline about this, but I discovered a field on the package that allows the API to associate the packages correctly:

![Screen Shot 2020-02-28 at 4.14.10 PM.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/2cfb7ef9-6c5a-4115-8fe1-f032f3ad211e)

This field must be filled out in order for us to "expand" the dcp_projectapplicant_dcp_package_applicant entity on the request.

**Comment by bfreeds** [comment]
Question:  

Since the Review Response Applicant must be filled out, but can only be one applicant, how will we show the status of the project (that it's in the "Edit PAS" stage) to other members of the applicant team?  

![image](https://user-images.githubusercontent.com/5316367/75694542-ac9ba800-5c76-11ea-8abc-83ccce83d1b8.png)

**Comment by hannahkates** [comment]
@bfreeds @allthesignals Update: instead of depending on the Applicant user's name being stored on the PAS package, we can filter all packages by the project by the package type. Anyone on the applicant team should be able to edit the visible packages.

**Comment by allthesignals** [comment]
```
https://dcppfsuat2.crm9.dynamics.com/api/data/v9.1/dcp_projects?$filter=dcp_dcp_project_dcp_projectapplicant_Project/any(o:o/_dcp_applicant_customer_value%20eq%20%20%27 contact-id %27)&$expand=dcp_dcp_project_dcp_package_project,dcp_dcp_project_dcp_projectapplicant_Project
```
