### ISSUE TITLE
Applicant team form

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#20]
## User Journey:
- User must fill in the Primary Applicant form.
- User can then add additional members to the applicant team by clicking one of the "Add team member" role buttons.
- Clicking on one of the "Add team member" buttons will generate an additional form for that new team member, with the role (Applicant, Representative, Environmental Consultant) displayed in the header the way that Primary Applicant is in the screenshot.

## Unresolved Questions:
- Should the completed member forms get collapsed or stay expanded and continue to be additive?

## [Figma Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP-Wireframes?node-id=0%3A1)
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/4f2b6760-35e1-457b-a8eb-3d530738f5cd)

## Implementation Notes

The Figma wireframes have more information on the exact names of the entities.

Consider encapsulating this inside its own component that receives an array of objects. New applicant information entities get pushed into that array through this form. The specific fields are available on the dcp_applicantinformation entity.

**Comment by allthesignals** [comment]
![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/5d6621d6-a58c-426c-8232-36bc75805c93)

Need to figure out what's going on here, what's teh difference

**Comment by bfreeds** [comment]
@allthesignals @hannahkates do you know which field represents the "role"?  Is this a coded value that maps onto the four role types ("Primary Applicant", "Co-Applicant", "Representative", and "Environmental Consultant"?)
![image](https://user-images.githubusercontent.com/5316367/80241240-40637200-8631-11ea-8372-367a3c1c9ff0.png)

**Comment by bfreeds** [comment]
@hannahkates  on the applicant information entities, I see two "types":
![image](https://user-images.githubusercontent.com/5316367/80255863-c4c2ee80-864b-11ea-9013-fb12f5ae6bf5.png)
Is this the field that we should be using for the 4 types we are using in the app? If so will they be added as valid options?  

Note this is separate in CRM from applicant information representative, which _does not_ have a "type" field.
