### ISSUE TITLE
Applicant Information Geographic State codes

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicant-portal#210]
These are numeric state codes: 

![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/b84f2541-8649-47d5-9a3e-ba99f6646d90)

We need to correctly serialize these or the request will fail

**Comment by hannahkates** [comment]
Good catch! This must be the cause of #183

**Comment by hannahkates** [comment]
Will be solved by #262
