### ISSUE TITLE
PAS BBL validation

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#212]
## What should happen:
Upon save, the BBLs added to the PAS form should be added to the table view of BBLs in Dynamics CRM. Each BBL should display the results of the validation that gets trigged upon save.
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/707061a4-e06e-43ee-a0b3-946a8a35f1d9)

## What happened instead:
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/2ddee557-8917-4e68-beb9-99b0349ebd41)

The BBLs are added to the table, but they aren't getting validated. This is probably because the project BBL entity `dcp_projectbbl` has the CRM project id `dcp_project`, borough `dcp_userinputborough`, block `dcp_userinputblock`, and lot `dcp_userinputlot` as individual **required** inputs. Those values can be [parsed out from the BBL](https://en.wikipedia.org/wiki/Borough,_Block_and_Lot).

`dcp_userinputborough` has an option set 
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/e7411431-d7e7-44c8-bd2c-cd0cf3cddee2)

**Comment by allthesignals** [comment]
Taking a look
