### ISSUE TITLE
PAS applicant team: clicking "organization" doesn't provide org input

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#214]
[Azure Requirement](#)

## What should happen:
In the PAS Applicant Team table, selecting "Organization" should conditionally display a form input for `dcp_organization` where the user should enter the organization name.
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/801d1507-cc82-4c59-985f-172de07a8f3c)

## What happened instead:
The form stays static without providing an input for the organization name.
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/95a24d5b-21cf-42cd-bb37-fc270b1a9f99)

**Comment by ksinghprod** [comment]
Sure Hannah, when this issue is resolved, We will retest and close our issue

**Comment by bfreeds** [comment]
Here's the logic for contextually showing the organization input:
![image](https://user-images.githubusercontent.com/5316367/81944252-7a89b900-95ca-11ea-948f-a1200f462db9.png)

`@applicant.dcpType` value is no longer "Organization", but the raw coded value (`717170000`).  This is why the this conditional is no longer working as expected.

**Comment by ksinghprod** [comment]
This issue is fixed @Hemachekuri 
![image](https://user-images.githubusercontent.com/57362229/82373954-60960f00-99ec-11ea-864c-cb071bc92c87.png)
