### ISSUE TITLE
PAS: completion year isn't saving and displaying

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#215]
## What should happen:
Upon saving the PAS form, the user should be able to refresh the form page and see the data they just saved.

## What happened instead:
The planned build year isn't saving properly to CRM. CRM expects a date for `dcp_estimatedcompletiondate`, so maybe we are incorrectly sending a string instead.

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/33ecce06-f134-4d23-bd99-4053490090e5)![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/e05ae573-66bf-4c49-9496-0cda8b073bc7)

## How to reproduce this bug:

1. Enter a build year on the PAS form
2. Click save
3. Go to CRM and see that the build doesn't appear there
4. Refresh the Applicant Portal PAS form page and see that the build year you thought you saved has disappeared.

**Comment by ksinghprod** [comment]
This issue is fixed @Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82375048-fbdbb400-99ed-11ea-82b8-b24a8a01714e.png)


![image](https://user-images.githubusercontent.com/57362229/82374964-d6e74100-99ed-11ea-9502-aeac3d8cc155.png)
