### ISSUE TITLE
Submitting PAS updates package to wrong status

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#216]
## What should happen:
Submitting the PAS package should update the package status to "Submitted"

## What happened instead:
Instead, the package status was updated to "Final Approval"

## How to reproduce this bug:

1. Enter the required data on a PAS form.
2. Click the Submit button
3. Go to package in CRM and see that package status is now "Final Approval" instead of "Submitted"

**Comment by allthesignals** [comment]
ah, yup — the code is explicitly doing it wrong... pr coming soon 
![image](https://user-images.githubusercontent.com/5004319/81723666-345d1a00-9451-11ea-9fb1-0a15d57325dd.png)

**Comment by ksinghprod** [comment]
This issue is fixed @Hemachekuri 
![image](https://user-images.githubusercontent.com/57362229/82373463-9ab2e100-99eb-11ea-8402-e4c554a5bb5c.png)

![image](https://user-images.githubusercontent.com/57362229/82373532-af8f7480-99eb-11ea-9953-ab3e38b06059.png)
