### ISSUE TITLE
View PAS button should appear for more package statuses

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#217]
## What should happen:
The "View Pre-Application Statement" button should appear for all packages that have been submitted or been reviewed.
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/688faf39-1f56-4620-80ba-4e3445912c47)

All inactive packages except 'Mistake'

## What happened instead:
A package with a status of "Final Approval" doesn't have a "View Pre-Application Statement" button.
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/dd782577-b76a-4877-8485-45bd08776040)

## How to reproduce this bug:

1. Find a package in CRM that has been submitted and now had a subsequent review-related status. eg. P2018X0175
2. Assign yourself to that package (if possible?) and login to Applicant Portal
3. See that project appears in bottom section without a "View Pre-Application Statement" button.

**Comment by allthesignals** [comment]
Let's talk @hannahkates — I need help understanding

**Comment by allthesignals** [comment]
![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/0e18e20e-5500-4958-8132-d68133375779)

I think we just need to add final approval

**Comment by allthesignals** [comment]
Need help reproducing issue... i was able to view your projects dashboard with e-mail param, but couldn't see any difference

**Comment by allthesignals** [comment]
217-show-final-approval is branch where i tried some code

**Comment by hannahkates** [comment]
@allthesignals Sadly I can't figure out how to change the package status to one of the later reviewed/approved statuses. I think the easiest fix is to make sure we're getting all visible, non-deactivated PAS packages. Out of those, we can then separate out the ones where the status = "Package Preparation" for the top section. Everything else would go at the bottom.

**Comment by bean75** [comment]
@allthesignals All inactive status packages should be shown except for 'mistake.'

**Comment by hannahkates** [comment]
We are going to eliminate the view and edit PAS buttons when we build the project page. Since we are building the project page next sprint, I don't think it's necessary to fix this bug. We would be fixing it, only to immediately remove this feature anyway.
