### ISSUE TITLE
RWCDS Project Description Section

### ISSUE THREAD

**Issue by nnxka** [NYCPlanning/labs-applicant-portal#222]
[Azure Requirement USER STORY 10972](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/10972)
[AB#10972](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10972)
[AB#10974](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10974)

### User Story
As an applicant, I want to complete the required project information needed from me in order so that I can save and submit my RWCDS application. 

### [Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP---Applicant-Portal?node-id=0%3A1)
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/7da543d5-8760-4d84-a542-67babec4e7fc)

## Display Logic
For "Identify and describe existing conditions" question: 
  - If `dcp_projectsitedescription` (RWCDS)  IS NULL, display `dcp_projectdescriptionproposedarea` (PAS)
  - If `dcp_projectsitedescription`(RWCDS) IS NOT NULL, display `dcp_projectsitedescription`
  - Write to `dcp_projectsitedescription`(RWCDS)  

For "Describe the proposed project" question: 
  - If `dcp_proposedprojectdevelopmentdescription` (RWCDS) IS NULL, display `dcp_projectdescriptionproposeddevelopment` (PAS)
  - If `dcp_proposedprojectdevelopmentdescription' IS NOT NULL, display `dcp_proposedprojectdevelopmentdescription' (RWCDS)
  - Write to the `dcp_proposedprojectdevelopmentdescription' (RWCDS)

For `dcp_constructionphasing` "Will construction be done in multiple phases?" question, 
- NULL should display as "Not Applicable"

## Backend
- Anticipated analysis year `dcp_buildyear` input should also write directly to the project record `dcp_anticipatedyearbuilt`
- Backend needs to query from PAS form data and get `dcp_projectdescriptionproposedarea` and `dcp_projectdescriptionproposeddevelopment`

**Comment by godfreyyeung** [comment]
Just tracking progress here:

- [x] Basic Project Description inputs (PR #401)
- [ ] In backend, write to project `dcp_anticipatedyearbuilt` as well
- [ ] Prefill fields from PAS form
