### ISSUE TITLE
Documents don't appear when navigating from the projects list

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicant-portal#229]
Go to /projects then click a package with documents. If there are already docs on that package, they won't show up. A hard refresh gets them to appear.

I think the attrs being provided in the request to /projects (which includes packages) does not include those documents. This is probably why, but I'm surprised that the forced reload on route transition didn't see those new docs attr...

**Comment by allthesignals** [comment]
@godfreyyeung 

I think this is because we use the deprecated "reload" hook. We got bit because we need to call "reload", but ready doesn't get re-run.

I think the current "transition path" would be to instantiate the file managers in the packages route, probably after awaiting the model in the model hook.

**Comment by Hemachekuri** [comment]
working fine upon refresh.
![image.png](https://images.zenhubusercontent.com/5ebc48df610bc025777641a4/7b941080-d6ba-4a9f-b9b7-225105a7e738)
