### ISSUE TITLE
Functional file upload

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#23]
## User Journey
- User sees a list of required files, along with hyperlinks to resources for providing the necessary attachments
- User can click "Choose Files" button and select files from their desktop.
- After clicking upload, the file names should be displayed on the page. They should be able to delete them by clicking the x icon.
- The "Choose Files" should stay enabled so that they can add more files.
- When the user clicks the "Save" the files will be sent to the PAS package on Sharepoint.
- When the users comes back to a saved package, the files they already saved should be listed (queried from CRM) and able to be deleted if desired.
- When the user clicks "Submit" the files will be sent to the PAS package on Sharepoint.
- Issue #10 covers functionality for clicking on link and opening file

## Required Attachments
- [ ] TAX MAP (if project area has more than one tax block submit a separate map for each tax block). 
   - **Provide hyperlink**: http://gis.nyc.gov/taxmap/map.htm
- [ ] OFFICIAL ZONING MAP (circle project area)
   - **Provide hyperlink**: https://www1.nyc.gov/site/planning/zoning/index-map.page
-  [ ] LAND USE MAP
   - **Provide hyperlink**: https://applicantmaps.planning.nyc.gov/
- [ ] SITE PLAN. Include building heights, unit counts and square footage calculations (GSF & ZSF) for proposed project (certain exceptions apply, consult the Lead Planner)
- [ ] PHOTOGRAPHS
- [ ] FOR PROJECTS IN THE NYC COASTAL ZONE ONLY: Map of project location within the NYC coastal zone including Special Area Designations
- [ ] FOR CITY MAP CHANGES ONLY:
  - Most Recent Borough President’s Final Section Map or Most Recent Approved and Filed Alteration Map for the Project Area 
    - **Provide hyperlink**: https://streets.planning.nyc.gov/about
  - Site Survey Recommended but Not Required
- [ ] SIGNATURE FORM
    - **Provide hyperlink**: https://www1.nyc.gov/assets/planning/download/pdf/applicants/applicant-portal/dcp-signature-form.pdf 

## [Figma Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP-Wireframes?node-id=0%3A1)
![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/4b2d4432-635b-43a6-8e04-01bca9a6673c)

## Implementation Notes
The backend will need to provide the currently uploaded files as well.

**Comment by hannahkates** [comment]
@bean75 I'm assuming we should only list the "REQUIRED" ones, and planners will individually flag to the applicant of they need to submit any of the conditional ones. Is that right?

![Screen Shot 2020-03-24 at 12.25.36 PM.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/9c049466-8edb-4dc8-a959-fe0d10ce693c)

**Comment by bean75** [comment]
If we omit, we need to make it clear that "Additional documents may be required depending on the nature of the proposal. Please consult the Lead Planner."

**Comment by bean75** [comment]
Also we need the signature form - or is that on a different item?

**Comment by hannahkates** [comment]
@bean75 Good catch on the signature form. I've added it as # 8.
