### ISSUE TITLE
In Proposed Development Site, In what year do you expect the development to complete? user is able to add text only 4 characters, as per dd, it should be date with feild length 8

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#230]
Browser(s) IE Browser and chrome

What should happen:
In Proposed Development Site,  In what year do you expect the development to complete? user  should be able to add  date with feild length 8
What happened instead:
In Proposed Development Site, In what year do you expect the development to complete? user is able to add text only 4 characters, as per dd, it should be date with feild length 8
How to reproduce this bug:
Log Into Applicant Portal
Click on the Edit Pre-Application Statement button
Navigate to the In Proposed Devlopment Site, and In what year do you expect the development to complete? user is able to add text only 4 characters, as per dd, it should be date with feild length 8

![image](https://user-images.githubusercontent.com/63460627/81829467-e86dac00-9508-11ea-9b37-eac293e3e22d.png)
![image](https://user-images.githubusercontent.com/63460627/81829566-09360180-9509-11ea-8933-8d2628a0e9f9.png)

**Comment by ksinghprod** [comment]
This issue is still not fixed, the field length is still 4, it should be 8

@Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82255353-7808c580-9922-11ea-83a6-ac1ec41fee66.png)

**Comment by hannahkates** [comment]
The year shows up correctly in CRM. The question only asks for the year, not including month and day. The current 4 character limit helps enforce better data quality for capturing the year. This app won't exist in the year 9999. I think we should close this issue.

**Comment by ksinghprod** [comment]
This issue is fixed as per Hannah's Comment @Hemachekuri
