### ISSUE TITLE
In PAS Form,  In Project Description, validation of 2000 characters in the fields are not consistent.

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#231]
Browser(s) IE Browser and chrome

## What should happen:
validation should be consistent across all feilds in Project Description input box for all feilds.
## What happened instead:
 In Project Description, 

**validation for 2000 characters is working good and displayed and save is disabled**
- Description of proposed CEQR scope

**validation for 2000 characters is not working good and displayed and save is not disabled**
- Description of the proposed development being facilitated by the land use actions, 
- Description of existing land uses and structures in the proposed Project Area and Development Site, 
- Description of land uses and built context in the surrounding area (within 1000 ft)

**user not able to enter more than 2000 characters and no validation is displayed**
- Why is this application being proposed? What is the legal, environmental, or land use background?, 
- What is the land use rationale for all the proposed actions?

## How to reproduce this bug:
Log Into Applicant Portal
Click on the Edit Pre-Application Statement button
Navigate to the In Project Description, 
Description of proposed CEQR scope - validation for 2000 characters is working good and displayed and save is disabled
Description of the proposed development being facilitated by the land use actions, Description of existing land uses and structures in the proposed Project Area and Development Site, Description of land uses and built context in surrounding area (within 1000 ft) - validation for 2000 characters is not working good and displayed and save is not disabled
Why is this application being proposed? What is the legal, environmental, or land use background?, What is the land use rationale for all the proposed actions? - user not able to enter more than 2000 characteres and no validation is displayed
![image](https://user-images.githubusercontent.com/63460627/81830045-924d3880-9509-11ea-8fc7-d5218c7d6997.png)
![image](https://user-images.githubusercontent.com/63460627/81830261-d93b2e00-9509-11ea-81e2-351d2545dcd8.png)

**Comment by hannahkates** [comment]
@Hemachekuri Thanks, I reformatted your description so it's easier to parse out as a checklist. GitHub issues can be formatted using markdown language: https://www.markdownguide.org/cheat-sheet/

**First set of bullet points:**
It sounds like the "Description of proposed CEQR scope" question has no unexpected behavior, correct?

**Second set of bullet points:**
The character limit for these three questions is 3000, not 2000, so I don't think this is a problem. Was 2000 a typo?

**Third set of bullet points:**
I think this is the only thing that needs to be updated. When the user reaches 2000 characters, we need to make sure they get a red "text is too long" message.

**Comment by godfreyyeung** [comment]
I'm going to take a look at this

**Comment by hannahkates** [comment]
@godfreyyeung I agree, I think that a x/2000 characters left countdown would be helpful.

**Comment by Hemachekuri** [comment]
working good.
![image](https://user-images.githubusercontent.com/63460627/82363809-59ff9b80-99dc-11ea-84ff-1266e0f3c113.png)
![image](https://user-images.githubusercontent.com/63460627/82363845-671c8a80-99dc-11ea-9145-d9420380c978.png)
