### ISSUE TITLE
In PAS Form, Project name is not displayed in the PAS Project name field under Project Information

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#233]
Browser(s) IE Browser and chrome

What should happen:
Project name is should be displayed in the PAS Project name field under Project Information
What happened instead:
Project name is not displayed in the PAS Project name field under Project Information
How to reproduce this bug:
Log Into Applicant Portal
Click on the Edit Pre-Application Statement button
Navigate to the In Proposed Information, Project name is not displayed in the PAS Project name field

![image](https://user-images.githubusercontent.com/63460627/81831419-51eeba00-950b-11ea-9a92-e4bedba95ddd.png)
![image](https://user-images.githubusercontent.com/63460627/81831469-65018a00-950b-11ea-99ce-5f59e22f1e92.png)

**Comment by ksinghprod** [comment]
Hi @hannahkates, changing this to sev2

**Comment by bean75** [comment]
@ksinghprod I don't see the urgency on this one - sev3/4 is fine by me, unless there is no other way to identify the current project name (then sev2)?

**Comment by hannahkates** [comment]
The only way to get the project name is to go back to the "my projects" dashboard and copy/paste it. Doable but annoying and confusing for the user.

**Comment by bean75** [comment]
If that is the only spot - what if they delete it and walk away and come back, will that cause confusion?
________________________________

**Comment by allthesignals** [comment]
Solve by removing the defaultValue stuff from the model and doing the handling in the route in the model hook.

**Comment by bfreeds** [comment]
@hannahkates should the value of the `project.dcpProjectname` be set equal to `package.dcpRevisedprojectname` when the user first comes to the PAS Form, or should `dcpRevisedprojectname` be kept null _until_ a user enters something in this input?

I'm not sure how dcpRevisedproject name is used and if setting those two values equal to each other would cause any confusion.

**Comment by bfreeds** [comment]
Nevermind - found that that would make the form dirty and activate the Save button.  Going to try keeping dcpRevisedprojectname null until a user overwrites the placeholder text (which will be the dcpProjectname)

**Comment by Hemachekuri** [comment]
working good. Hence closed the bug.

![image](https://user-images.githubusercontent.com/63460627/82470053-d5bc1f80-9a92-11ea-89a6-946358ff6eb6.png)
![image](https://user-images.githubusercontent.com/63460627/82470110-e8ceef80-9a92-11ea-9902-d2c37110ea1d.png)
