### ISSUE TITLE
RWCDS Increment of Analysis 

### ISSUE THREAD

**Issue by nnxka** [NYCPlanning/labs-applicant-portal#236]
[Azure Requirement 10972](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/10972)
[AB#10972](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10972)
[AB#10974](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10974)

### User Journey
- User must select click "add site" to get a new form interface to pop-up
- The form will get appended onto the page. 
- The user must fill in details about the site
- After the saving the action, they can click " + Add Action" to add another type of action.

### [Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP---Applicant-Portal?node-id=0%3A1)
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/223bace8-c91c-490c-888e-334b68fe9558)

**Comment by hannahkates** [comment]
Closing, since this content will be captured in a spreadsheet attachment
