### ISSUE TITLE
When the Applicant enters the Organization/Authorized Representative information in the Applicant Team section, the information entered displays in the Applicant Information grid on CRM

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#238]
## Browser(s) and Device(s) observed on:
Chrome, Firefox, IE

## What should happen:
When the Applicant enters the Organization/Authorized Representative information in the Applicant Team section from the Applicant Portal, the information entered should be displayed in the Authorized Representative Information grid on CRM

## What happened instead:
 the information entered by the applicant displays in the Applicant Information grid on CRM not the Authorized Representative Information

## How to reproduce this bug:
1 Log into the Applicant Portal
2 Click on the Edit Pre-Application Statement button
3 navigate to the Applicant team section
4 select the organization radio button
5 enter data for all fields in the applicant team section and save
6 log into UAT2 CRM, open the same project, PAS form
7 navigate to the Prospective Applicant/Representative Contact section (error displayed here)

![image](https://user-images.githubusercontent.com/57362229/81842431-01cb2400-951a-11ea-9c4a-a2d8d1194f2d.png)

![image](https://user-images.githubusercontent.com/57362229/81842472-10194000-951a-11ea-93a7-6ab2b687fc84.png)

![image](https://user-images.githubusercontent.com/57362229/81842565-37700d00-951a-11ea-9324-2bfda577f4cb.png)

**Comment by bean75** [comment]
This is not a bug, it is functioning as designed - I believe we discussed the clarification needed is to call "Authorized Applicant Representative" an "Authorized Organization Representative."

**Comment by ksinghprod** [comment]
Closing this bug as per Aline's Comment 
@Hemachekuri
