### ISSUE TITLE
Sticky side bar with progress checklist

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#24]
## User journey
- As the user fully completes each section of the form, the progress checklist will indicate which sections have been fully filled in
- The Save and Submit buttons scroll with it on the right hand side.

## Unresolved
What validation should be used to determine completeness?

## Figma Wireframes
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/962ebe1f-9d1e-4693-af5c-5238a80a2675)

**Comment by allthesignals** [comment]
There are a few scrollspy addons for this sort of thing
