### ISSUE TITLE
When the Applicant clicks on and adds other team member, the data saves as an applicant type in CRM, not in the Authorized Applicant Representative grid

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#240]
## Browser(s) and Device(s) observed on:
Chrome, IE, Firefox

## What should happen:

When the Applicant clicks on and adds other team member, the data should save as (type) Authorized Applicant Representative in CRM, not (type) Applicant 

## What happened instead:
the data saved as an applicant type in CRM, not Authorized Applicant Representative (type) 

## How to reproduce this bug:

1. Log into applicant Portal
2. Click on the Edit Pre-application statement button
3. navigate to the applicant team section
4. click on the add other team member button
5. enter information and click save
6. log into UAT2 CRM and go to the same PAS form/package
7. Navigate to the the Prospective Applicant/Representative Contact section (error is displayed here)

![image](https://user-images.githubusercontent.com/57362229/81846169-ac921100-951f-11ea-9706-7c0f01281df5.png)

![image](https://user-images.githubusercontent.com/57362229/81846244-c2073b00-951f-11ea-9149-b0cf509a526d.png)

**Comment by bfreeds** [comment]
When a user clicks `Add Other Team Member` and saves, the `Team Member` should not appear in the second table on the Applicant team on the PAS Form "Applicant Representative Information."

Need to investigate why the records being added through `Add Applicant Team Member` is being posted to the incorrect table.  
![image](https://user-images.githubusercontent.com/5316367/81855704-b02c9480-952d-11ea-8b02-9d1dac019d1b.png)

**Comment by bfreeds** [comment]
Likely same root cause as #238

**Comment by ksinghprod** [comment]
Hi @hannahkates  retested this bug with new modified "Add other team member button", the added other team member is still displaying in the applicant grid/table on CRM 

cc: @Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82240356-4d117800-9908-11ea-9aca-d2f2d54013c7.png)

![image](https://user-images.githubusercontent.com/57362229/82240548-9a8de500-9908-11ea-9bb8-916d880c5f8a.png)

**Comment by bfreeds** [comment]
@ksinghprod @hannahkates I opened a draft pr (#260) that may have moved this to the wrong zenhub pipeline -- the fix to this and #238 are being addressed in that PR (which is still work in progress).

**Comment by bean75** [comment]
The assumptions here are incorrect!! Authorized Applicant Representatives do not/should not appear in the second grid.

There is a VERY big difference between an 'authorized applicant representative' and an "applicant representative." 
Authorized Applicant representatives are the entry for organizational applicants (companies, non-profits, city agencies that are applicants) and should appear in the first grid - they are the humans that can sign for an organization (CEO, Commissioner, etc.).

Applicant representatives are land use attorneys and environmental reps and agency staff that work on the application submission for the applicant regardless of whether or not the applicant is a human or an organization. They appear in the second grid.

**Comment by bean75** [comment]
Note per discussion today that the Authorized Applicant Representatives  should be called "Authorized Organizational Representative" on the Applicant portal side to avoid confusion.

**Comment by hannahkates** [comment]
I'm working on a PR for #288 which updates the label to say "Authorized Organization Representative"

**Comment by bfreeds** [comment]
@bean75 than you for clarifying, that was my understanding from our earlier conversation.
> Note: the expected behavior is that clicking add Applicant with radio button Individual results in a CRM record in the first table (Applicant Information) with type=Applicant. If the radio button is Organization, then the type=Authorized Applicant Representative. If a user adds an Applicant Team Member, the CRM record will appear in the second table Applicant Representative Information.

**Comment by bean75** [comment]
@brandyn that note seems correct to me!
________________________________

**Comment by hannahkates** [comment]
Reopening and marking as "resolved"

**Comment by ksinghprod** [comment]
This issue is fixed 
@Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82359042-5fa5b300-99d5-11ea-905a-0a4f7ef0bb98.png)

![image](https://user-images.githubusercontent.com/57362229/82359119-7ba95480-99d5-11ea-8d9d-8a1c50adb595.png)
