### ISSUE TITLE
Revise PAS land use action component

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#245]
## User context
From applicant feedback in a recent demo, it was determined that we can reduce confusion for users by eliminating an unnecessary question in the land use action component.

Currently, all actions require a question asking how many of that type of action there are. It turns out it's only possible to have one of most types of actions, so we can safely assume that the answer is one in those cases.

Only three land use actions require the "how many" question:
- Zoning Special Permit, dcp_pfzoningspecialpermit 
- Zoning Authorization, dcp_pfzoningauthorization 
- Zoning Certification, dcp_pfzoningcertification 

### Display and Model Logic
Only Zoning Special Permits, Authorizations, and Certifications require the "how many" question. 

For the rest of the zoning actions, that question should be hidden. When the user adds one of the other actions, the number 1 should be saved to the model for that action.

### Updated wireframe for actions with no questions
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/469df3bc-0b47-499a-9566-d414c2f6b5bb)

**Comment by hannahkates** [comment]
@trbmcginnis I'm assigning you to this since you're already assigned to other land use action issues. I want to make sure you're not fixing validations for some fields that we don't need user validation for anymore.

**Comment by hannahkates** [comment]
@ksinghprod @Hemachekuri Tagging so you're aware of this planned change

**Comment by ksinghprod** [comment]
For the listed 3 selection in the issue, all are working fine 
![image](https://user-images.githubusercontent.com/57362229/82242213-7bdd1d80-990b-11ea-8a0a-79233747fcfc.png)

![image](https://user-images.githubusercontent.com/57362229/82242269-91eade00-990b-11ea-9938-f062cc3e2a26.png)

**Comment by hannahkates** [comment]
Thanks @ksinghprod  should this issue be closed then?

**Comment by Hemachekuri** [comment]
Closing the issue as it is working good.


![image](https://user-images.githubusercontent.com/63460627/82604462-5e65b900-9b82-11ea-82b6-61c42b680183.png)
