### ISSUE TITLE
In Project Information, in Project Name, user is able to enter unlimited characters.

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#249]
Browser(s) IE Browser and chrome

What should happen:
In Project Information, in Project Name, user should not be able to enter unlimited characters and limit to 50 Characters as per DD.
What happened instead:
In Project Information, in Project Name, user is able to enter unlimited characters.
What happened instead:
How to reproduce this bug:
Log Into Applicant Portal
Click on the Edit Pre-Application Statement button
Navigate to the Project Information, in Project Name, user is able to enter unlimited characters.

In Project Information, in Project Name, user is able to enter unlimited characters.

![image](https://user-images.githubusercontent.com/63460627/81948748-14079980-95d0-11ea-9070-2062cd0c8ee4.png)

**Comment by allthesignals** [comment]
Addressed by https://github.com/NYCPlanning/labs-applicant-portal/pull/295

**Comment by Hemachekuri** [comment]
working good. Hence closed.
![image](https://user-images.githubusercontent.com/63460627/82469870-9d1c4600-9a92-11ea-8ecb-f727cdf30c46.png)
