### ISSUE TITLE
The fields lengths on the the PAS Form are too long

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#252]
[AB#10528](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10528)

## Browser(s) and Device(s) observed on:
Chrome, IE, Firefox

## What should happen:

Fields lengths on the PAS form should match the CRM PAS Form and the PAS form Data Dictionary  

## What happened instead:
The Listed field names in the attached spreadsheet are greater than the expected field limits 

## How to reproduce this bug:

1. Log into Applicant Portal
2. Click on the Edit Pre-Application Statement Button
3. Navigate to listed sections, field names on the PAS Form and enter data that is greater than the listed field character limit (error happens here)

[PAS Form field lengths.xlsx](https://github.com/NYCPlanning/labs-applicant-portal/files/4630446/PAS.Form.field.lengths.xlsx)

**Comment by trbmcginnis** [comment]
Fields that have length validations:

- [ ] `dcpRevisedprojectname`

**Comment by hannahkates** [comment]
It looks like this was already resolved in #336. Ready for retest.
