### ISSUE TITLE
Certain conditional fields on the PAS Form are getting validated by the system without the user's input and are displaying the CRM schema name

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#253]
## Browser(s) and Device(s) observed on:
Chrome, IE, Firefox

## What should happen:
Conditional fields should allow the user to enter data/input and then validate 

## What happened instead:
When the listed questions were answered with a yes, the system validated the conditional field and displayed the schema name
##
![image](https://user-images.githubusercontent.com/57362229/81977900-b9cefe80-95f8-11ea-8cb7-f9da2c4d3b93.png)

##
![image](https://user-images.githubusercontent.com/57362229/81977970-ce12fb80-95f8-11ea-91e8-8f40f7358122.png)

##
![image](https://user-images.githubusercontent.com/57362229/81978010-de2adb00-95f8-11ea-9db2-4bf1449ce902.png)

## How to reproduce this bug:

1. Log into CRM
2. Click on the Edit Pre-Application Statement button 
3. Navigate to the fields show above in the screenshots and select yes (error Happens here)

**Comment by allthesignals** [comment]
Interesting, yep, this is doable, and we should allow user to at least _try_ to do the right thing first. Could use tasks for something timer based. Or wait to validate.

The reason the validation is so aggressive _now_ is because previously it was very easy for a user to end up in a completely invalid state if the user turned the conditional on then off. Hence the current setup.

@andycochran any thoughts on this one? It's pretty minor but def annoying.

**Comment by hannahkates** [comment]
This is how it looks now. I think it's acceptable - it feels more helpful and less aggressive with the new text. User a timer feels over-engineered.

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/7f31e728-3407-4610-909c-c8d46e66f8fa)

**Comment by trbmcginnis** [comment]
@hannahkates Engineers & design talked this morning about how our implementation of this would be best decided after user testing (to see if users feel the immediate validation is aggressive or prefer it that way). Can I mark this as resolved until we're able to conduct user testing?

**Comment by hannahkates** [comment]
Ok I agree. @ksinghprod @Hemachekuri We're not planing to fix this unless users complain.

**Comment by ksinghprod** [comment]
this issue is fixed for now, may be reopened if user complain @Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82381491-4cf0a580-99f8-11ea-8d5d-0cb6f89fc0dc.png)
