### ISSUE TITLE
Upon submission the PAS Form, the under the applicant team, The full name of the applicant displays the dcp schema name

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#256]
## Browser(s) and Device(s) observed on:
Chrome, IE, Firefox

## What should happen:
Under the Applicant Team, upon submission of the PAS Form user should be able to the the full name entered by him/her

## What happened instead:
Upon submission the user is able to see the dcp schema name as well listed next to the applicant;s full name

## How to reproduce this bug:

1. log into the applicant portal
2. click on the Edt-PAS Statement button
3. Under applicant team, enter information for individual and organization's information
4. save and submit
5. Error will be seen here  

NOTE: User is able to create,save, and submit blank applicant team members, please see screenshot for reference 

![image](https://user-images.githubusercontent.com/57362229/81984474-d40dda00-9602-11ea-8b8b-43753a520863.png)

**Comment by hannahkates** [comment]
Might make sense to tackle this with #258 since they're in the same view-only template.

**Comment by andycochran** [comment]
Addressed by b4ad95e5b2fe182b31c49ea10433a1b81dfb70f5.

**Comment by Hemachekuri** [comment]
Working good. Hence closed the defect
![image.png](https://images.zenhubusercontent.com/5ebc48df610bc025777641a4/0183a0c9-a5c9-4be3-a09b-225c59654a9d)
