### ISSUE TITLE
In Proposed Land Use Actions, all drop down fields in ADD Proposed Action, such as Change in CityMap should not allow for alphabets, are currently allowing "e"

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#257]
Browser(s) IE Browser and chrome

What should happen:
In Proposed Land Use Actions, all drop down fields in ADD Proposed Action,  select Change in CityMap user not be able to enter alphabets except "e" , as per DD it is a text feild. It should allow all alphabets and numbers. Number is allowed which is correct, but unable to enter enter alphabets except "e"
What happened instead:
In Proposed Land Use Actions, all drop down fields in ADD Proposed Action,  select Change in CityMap user not be able to enter alphabets except "e" , as per DD it is a text feild. Number is allowed which is correct, but unable to enter enter alphabets except "e"Number is allowed which is correct, but unable to enter enter alphabets except "e"

How to reproduce this bug:
Log Into Applicant Portal
Click on the Edit Pre-Application Statement button
Navigate In Proposed Land Use Actions, all drop down fields in ADD Proposed Action,  select Change in CityMap user not be able to enter alphabets except "e" Number is allowed which is correct, but unable to enter enter alphabets except "e"

![image](https://user-images.githubusercontent.com/63460627/81985458-4af7a280-9604-11ea-8085-e960e370464c.png)

**Comment by trbmcginnis** [comment]
`e` stands for exponent which is why it's allowed in an input type of "number". Will investigate if we can disallow that

**Comment by allthesignals** [comment]
@trbmcginnis can we look at this component? I'm still seeing some issues on develop.

**Comment by ksinghprod** [comment]
This issue is now fixed @Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82606578-4d6a7700-9b85-11ea-82c9-0ec999aff6b4.png)
![image](https://user-images.githubusercontent.com/57362229/82606627-6410ce00-9b85-11ea-8b15-de454d3a10ac.png)
