### ISSUE TITLE
PAS "Save"

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#26]
Clicking the "Save" button on the PAS page should post to CRM whatever data is filled in to the PAS package form.

**Status to update:**
The PAS package form status should stay set to “Package Preparation”

**Attributes to send:**
**[See wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP---Applicant-Portal?node-id=0%3A1)**

## Implementation Notes

In terms of model validation, there's a difference between being able to "save" and being able to "submit". Because related entities get created in addition to the pas form itself, saving/submitting implicitly creates new records, and those records themselves might have their own minimum required fields/validations. Because of that, "saving" might not be just a matter of saving anything and everything, but include its own level of validation.

**Comment by allthesignals** [comment]
Hmm we need to figure out if there'll be an issue bt saving and "submitting". I think the act of submitting something is implicitly triggered by updating the statecode of an entity.

**Comment by bean75** [comment]
I think you are correct. They are two different processes generally, but I think submitting also saves? Not entirely clear to me. There are many things that automatically happen when a package is 'submitted'
________________________________
