### ISSUE TITLE
PAS "Submit"

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#27]
Submission is only possible after saving. Clicking the "Submit" button on the PAS page should post to CRM all the data filled in to the PAS package form. Clicking this button should trigger the transition to the confirmation age.

## Status to update:
The PAS package form status should update to "Submitted"

## Attributes to send:
**[See wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP---Applicant-Portal?node-id=0%3A1)**

NOTE: Submitting some attributes to the PAS Package SHOULD trigger an automatic update on the dcp_project record as well as on the package. We should check this once we build the functionality.

**dcp_project fields that should get auto-updated by CRM**
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/425d7415-cbed-4f7f-966d-248716b45d10)

**Comment by bean75** [comment]
Labs should not have to update the project record - just adding to the form should cause MCS to automatically update the project record. Liz could confirm but I think we picked those field s to remain because they do auto populate already.

**Comment by hannahkates** [comment]
@Eabrante do you know if that's true, that submitting the PAS auto sends data to the project record? That would be great if we don't need to trigger it separately. Testing may be the only way to confirm 100% that changing the PAS status to "Submitted" actually triggers this on its own.

**Comment by bean75** [comment]
@hannahkates I would assume yes. We had never planned for additional data mapping that wasn't already developed in CRM.

**Comment by trbmcginnis** [comment]
@hannahkates From looking at the metadata spreadsheet I'm assuming `statuscode` is the field to update with "Submitted"?

This field has three options"

```"States:
1: Active
2: Inactive
717170000: Submitted"```

**Comment by Eabrante** [comment]
> @hannahkates From looking at the metadata spreadsheet I'm assuming `statuscode` is the field to update with "Submitted"?
> 
> This field has three options:
> 
> ```
> 1: Active
> 2: Inactive
> 717170000: Submitted"
> ```

Hi @trbmcginnis , the scheme field might be 'statecode' for the package status.

**Comment by Eabrante** [comment]
@trbmcginnis , nope you are right. Its 'statuscode'. 

![image](https://user-images.githubusercontent.com/43378798/81213471-64657280-8fa4-11ea-9b89-4cb8c25061e7.png)

**Comment by trbmcginnis** [comment]
Because the **Save** button is what sends data to the CRM database the **Submit** button will:

1) update the `statuscode` field on a PAS package to "Submitted"
2) transition away from the pas-form edit page

So I'm thinking the Submit button should stay **disabled** (or the user clicks it and a warning pops up not allowing them to transition routes) until... 

- there are no Dirty Attributes (the user has clicked Save after making changes)
-  all inputs have text in them
- all radio buttons are selected
- there's at least one file
- there's at least one applicant
- there’s at least one bbl
- there's at least one action

@hannahkates is EVERY field on the pas-form required for users to continue? Or are some fields required and others just suggested?

**Comment by hannahkates** [comment]
@bean75 can you confirm if the validations listed in bullet points in Taylor's comment ^^ are correct? should any of the questions be optional where it's ok to leave a text input blank or radio button unchecked?

**Comment by hannahkates** [comment]
@trbmcginnis @bean75 Liz is going to follow up with the list for what is required @Eabrante

**Comment by Eabrante** [comment]
@hannahkates @trbmcginnis , the PAS form has very few required fields. All other fields on the current CRM form are optional except when a conditional question is answered and a follow up question is then required.
![image](https://user-images.githubusercontent.com/43378798/81221873-6c77df00-8fb1-11ea-9775-cb23bb2f7568.png)

I create a data dictionary of PAS form fields. The doc contains all fields on PAS form and their criteria. Including the conditional questions and required follow up questions.
- https://nyco365-my.sharepoint.com/:x:/r/personal/eabrante_planning_nyc_gov/Documents/Remote%20Project%20Work/DCP%20Portals/PAS%20Form/ZAP_PAS%20Form%20Field%20Data%20Dictionary.xlsx?d=w5421d03a09454d2d9183aad706351e2d&csf=1&web=1&e=OZdOrO

**Comment by trbmcginnis** [comment]
Thanks @Eabrante! That's super helpful. I am unable to access that sharepoint link, I might not have permission?

**Comment by bean75** [comment]
Letting Liz handle the data dictionary on the field specific validations to aid in this, but in general we don't want to go heavy on validation, so I would prefer we match the validation on the CRM side with a couple exceptions (if they are easy to do) as noted to revised list below. Also added some corrections...


So I'm thinking the Submit button should stay disabled (or the user clicks it and a warning pops up not allowing them to transition routes) until...

  *   there are no Dirty Attributes (the user has clicked Save after making changes)
  *   all required fields have text in them (only fields required in CRM)
  *   all radio buttons are selected (if required)
  *   there's at least one file (additional)
  *   there's at least one applicant (additional)
  *   there’s at least one bbl - No some projects will not take place on tax lots, but in streets, waterways, etc that do not have BBLs.
  *   there's at least one action (additional)

^^ note: there are other validations (like text length) that are in place BEFORE a user can Save.

________________________________

**Comment by Eabrante** [comment]
> Thanks @Eabrante! That's super helpful. I am unable to access that sharepoint link, I might not have permission?

@trbmcginnis , you have access to the file. It should prompt you to log in with DCP credentials.

**Comment by trbmcginnis** [comment]
@Eabrante Unfortunately, I do not think that I have access to the file. Even when I am signed in to Sharepoint, I get this when I click on the link. Is there another link that you can share, or a file that you could email me?

![Screen Shot 2020-05-07 at 9.11.47 AM.png](https://images.zenhubusercontent.com/5ca36b1555cfe32f2f66b411/a77f5a3a-83cc-4821-ab5a-9aea92372f49)

**Comment by trbmcginnis** [comment]
Required fields that we are currently using in the app:
- dcp_projectname
- dcp_firstname (for representative and applicant)
- dcp_lastname (for representative and applicant)
- dcp_email (for representative and applicant)

Required fields that we are currently NOT using in the app:
- dcp_name
- dcp_type
- dcp_pasprojectname

**Comment by bean75** [comment]
I thought you were using dcp_type? How else are you identifying whether or not the applicant is an organization or not? (It is needed for the applicant contact records to function properly)





________________________________

**Comment by trbmcginnis** [comment]
All "Required" PAS Form Fields

**Used in the app:**
dcp_projectname
dcp_urbanareaname
dcp_pleaseexplaintypeiienvreview
dcp_projectareaindutrialzonename
dcp_projectarealandmarkname
dcp_proposeddevelopmentsiteotherexplanation
dcp_inclusionaryhousingdesignatedareaname
dcp_housingunittype
dcp_firstname
dcp_lastname
dcp_email
dcp_type (will be added in issue #162)
** all "extra questions" that are part of land use actions are required once a user selects the action

**Not used in the app:**
dcp_pasprojectname
dcp_version
dcp_informationalmeetingheld
dcp_name

**Comment by Eabrante** [comment]
@trbmcginnis the applicant information is on a separate entity that populates the form. See the data dictionary tab for applicant information.

**Comment by trbmcginnis** [comment]
@Eabrante Sorry for the confusion -- that list was just including any fields that had Required = "Yes" (excluding land use action attributes) so I could provide easy access to the field names in the issue content. Our models in our frontend app correspond to the entities that we will be checking the fields on (e.g. applicant model, pas-form model, and project model), so the attributes are all already organized according to the entity. I will add extra details to that list to avoid confusion.

**Comment by ksinghprod** [comment]
This issue is now fixed @Hemachekuri 

Please see defect #314
