### ISSUE TITLE
User is not able to delete/x out the selections made from the Proposed Land Use Actions drop down list

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#270]
## Browser(s) and Device(s) observed on:
Chrome, IE, Firefox
## What should happen:
When a user makes a selection from the Proposed Land Use Actions Drop Down List, User should be able to delete the selection he/she has made by clicking on the delete button 

## What happened instead:
When a user makes a selection from the Proposed Land Use Actions Drop Down List, User is not able to delete the selection he/she has made

## How to reproduce this bug:

1. Log in to Applicant Portal
2. Click on the Edit-Pre Application Statement button
3. navigate to the Proposed Land Use Action section
4. Make 2-3 selections and save
5. click on the delete button (error happens here)

![image](https://user-images.githubusercontent.com/57362229/82092376-2adce780-96c7-11ea-8147-784d0010ba8f.png)

**Comment by trbmcginnis** [comment]
Solved with PR #264

https://github.com/NYCPlanning/labs-applicant-portal/pull/264

**Comment by hannahkates** [comment]
Thanks @trbmcginnis ! Marking with the "Resolved" label

**Comment by ksinghprod** [comment]
This is fixed 

@Hemachekuri 
![image](https://user-images.githubusercontent.com/57362229/82250914-53a8eb00-991a-11ea-8ab7-141338f62749.png)

![image](https://user-images.githubusercontent.com/57362229/82250969-6c190580-991a-11ea-87a7-d62073abaa51.png)
