### ISSUE TITLE
Updated Proposed Development site information in all fields and saved and submitted. But is not  updated correctly in CRM

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#273]
## What should happen:
Updated Proposed Development site information in all fields and saved and submitted. But is not  updated correctly in CRM
## What happened instead:
Updated Proposed Development site information in all fields and saved and submitted. submitted data should be updated correctly in respective fields in CRM
## How to reproduce this bug:

Log in to Applicant Portal
Click on the Edit-Pre Application Statement button
navigate to the Proposed Development site information
Enter required data and select in the check boxes  and save
click on submit
Updated Proposed Development site information in all fields and saved and submitted. submitted data should be updated correctly in respective fields in CRM

![image](https://user-images.githubusercontent.com/63460627/82093977-2f56cf80-96ca-11ea-849d-56ad27747b68.png)

![image](https://user-images.githubusercontent.com/63460627/82094072-5a412380-96ca-11ea-825d-b495ea9085fc.png)

**Comment by bean75** [comment]
Were all required fields filled in?

**Comment by allthesignals** [comment]
Hi @Hemachekuri it'd help me a lot if you could post the link to these sites, even if just the package id.

**Comment by allthesignals** [comment]
Having trouble reproducing this.

![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/b2865c63-376f-419c-8d95-439d6d431fbc)

Are you sure it's still an issue? Can you provide a link?

**Comment by ksinghprod** [comment]
this issue is now fixed  @Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82585738-821a0680-9b64-11ea-89b6-ee4b0865c8d8.png)



![image](https://user-images.githubusercontent.com/57362229/82585755-8cd49b80-9b64-11ea-90de-bfec9971fe0c.png)


![image](https://user-images.githubusercontent.com/57362229/82585782-99f18a80-9b64-11ea-81f8-4db7044ad8f9.png)
