### ISSUE TITLE
When A BBL on the PAS Form is deactivated from the CRM side, the same BBL is still present on the PAS form on the Applicant Portal

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#274]
## Browser(s) and Device(s) observed on:
Chrome, IE, Firefox

## What should happen:

When a BBL on the Project record, or PAS Form is deactivated from CRM, it should not be displayed on the PAS Form on the Applicant Portal

## What happened instead:
After the Deactivation of the BBL on the Applicant Portal PAS Form displays the deactivated BBL 

## How to reproduce this bug:

1. Log In the Applicant Portal
2. Add a BBL and save
3. log into CRM UAT2, navigate to the same project, PAS Form
4. navigate to the Project Area Geographic information Section  
5. click on the BBL added from step 2 and deactivate it and save
6. wait a couple of minutes and log back into the Applicant Portal, navigate to the same PAS Form
7. Navigate to the Project Geography section (error will be seen here) the BBL will still be displayed

![image](https://user-images.githubusercontent.com/57362229/82095291-cae93f80-96cc-11ea-8299-88e2b16ce4b6.png)

![image](https://user-images.githubusercontent.com/57362229/82095359-e3f1f080-96cc-11ea-9288-7859180785ae.png)

**Comment by allthesignals** [comment]
I think it's not filtering out deactivated bbls

**Comment by bean75** [comment]
@allthesignals @hannahkates It should filter out deactivated BBLs - pretty important support functionality that we need if applicants run into issues.

**Comment by allthesignals** [comment]
I pushed a fix up last night?

**Comment by hannahkates** [comment]
Oh ok good. Since the issue didn't get connected to a PR or labeled as "Resolved" in the ready for retest column it seemed like it still open.

**Comment by allthesignals** [comment]
sorry my bad

**Comment by ksinghprod** [comment]
This issue is fixed @Hemachekuri 
![image](https://user-images.githubusercontent.com/57362229/82260889-0fbee180-992c-11ea-8769-4806ab29f98c.png)

![image](https://user-images.githubusercontent.com/57362229/82260979-341abe00-992c-11ea-9473-42131f1f8a6a.png)


![image](https://user-images.githubusercontent.com/57362229/82260912-19484980-992c-11ea-9c4f-4ae2e885676f.png)
