### ISSUE TITLE
In Proposed Land Use action section, for conditional fields, the User is unable to enter data, nor is he/she given instructions that input is not required

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#285]
## Browser(s) : IE and Chrome

**EDIT: Seem like as per issue #245 , only 3 selections should have conditional questions that require the applicant's answers** 
Zoning Special Permit
Zoning Authorization
Zoning Certification

**Discussed with @hannahkates , that the conditional fields that show up upon selection, that do not require an answer from the applicant should be a little bit more clear**

## What should happen:
User should receive some sort of instruction for conditional fields that do not require an answer from the Proposed Land Use Section Drop down selection
## What happened instead:
User is unable to enter data in the Proposed action input text boxes, for the conditional fields, and is unaware that he/she does not need to input any values
## How to reproduce this bug:

Log in to Applicant Portal
Click on the Edit-Pre Application Statement button
navigate to the Proposed Land Use action
select Change in CityMap or any item from drop down
User is unable to enter required data in input text box, there no instructions present

![image](https://user-images.githubusercontent.com/63460627/82228153-c30ce380-98f6-11ea-9e58-c89d073282e1.png)

**Comment by bean75** [comment]
Other fields have conditional questions. Those are the only three that require the numeric entry for how many actions?

**Comment by hannahkates** [comment]
Correct, this issue is only referring to actions that don't have any condition questions. They will appear like this so it's less confusing:

![image](https://user-images.githubusercontent.com/13967925/82248327-ec893780-9915-11ea-99ec-8a1a4bdf5ad2.png)

**Comment by ksinghprod** [comment]
This issue is fixed, @Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82382287-b3c28e80-99f9-11ea-9ea1-a0a062c29ab3.png)
