### ISSUE TITLE
In Project Geography, Tax Lots Included in This Project for the address is displayed twice when user inputs address.

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#286]
## What should happen:
In the Project Geography
Input the address in Add tax lots by searching for an address or BBL
Tax Lots Included in This Project for the address is displayed twice.
## What happened instead:
In the Project Geography
Input the address in Add tax lots by searching for an address or BBL
Tax Lots Included in This Project for the address should display only once.
## How to reproduce this bug:

Log in to Applicant Portal
Click on the Edit-Pre Application Statement button
navigate to theProject Geography
Input the address in Add tax lots by searching for an address or BBL
Tax Lots Included in This Project for the address is displayed twice.

**Comment by hannahkates** [comment]
It's only displaying once for me. Is this happening every time for you or only intermittantly? 
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/23695ac3-3a78-4547-8fc3-773543a402d3)

**Comment by allthesignals** [comment]
Do you have a screenshot @Hemachekuri?

**Comment by Hemachekuri** [comment]
working good. Hence closed the defect
![image](https://user-images.githubusercontent.com/63460627/82369364-e3b36700-99e4-11ea-8fee-7af729c89c6b.png)
