### ISSUE TITLE
Display PAS revision number

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#29]
## User journey:
Users should only see active, unsubmitted PAS packages OR the most recent inactive submitted ones. They should not see the older inactive revisions. **If there are multiple revisions, we should display the revision number.**

## Logic
Need to look at the data to figure out the exact fields and values to use

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/d7a0abe2-c91d-49e0-af4b-d16686f195c8)

**Comment by bean75** [comment]
I think perhaps we just display a package version number?
Is that what you mean?
________________________________

**Comment by hannahkates** [comment]
@bean75 I think that would work, but we need to understand how we will know if it's a revision and avoid showing the same project more than once if there are multiple revisions. Is it MVP for them to be able to see prior revisions?

**Comment by bean75** [comment]
I am ok with them only seeing the current package that is active with a version number. and hiding the inactive ones for now.
________________________________
