### ISSUE TITLE
Applicant is able to upload but not save a document on the PAS Form

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#290]
[AB#10532](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10532)

## Browser(s) and Device(s) observed on:
Chrome, IE, Firefox

## What should happen:
User should be able to upload and save documents on the PAS Form, in the Attached Documents Section

## What happened instead:
Applicant is able to upload but not save a document on the PAS Form
## How to reproduce this bug:

1. Log into the Applicant Portal
2. Click on the Edit Pre-Application Statement Button
3. Navigate to the Attached Documents Section 
4. click on the choose files
5. select a file and save (after saving document disappears)

![image](https://user-images.githubusercontent.com/57362229/82243747-1a6a7e00-990e-11ea-9f50-b3b6f5bf93a5.png)

After Saving 

![image](https://user-images.githubusercontent.com/57362229/82243791-2c4c2100-990e-11ea-9eee-e0a0a5f7a455.png)

**Comment by allthesignals** [comment]
it does upload, it just disappears. this is documented in an issue somewhere. can you find it and make sure it's not a dupe?

**Comment by hannahkates** [comment]
It's documented in #229. I'll put this in the duplicates column.

**Comment by ksinghprod** [comment]
After uploading and saving the user needs to refresh the page, still will keep this bug open

**Comment by Hemachekuri** [comment]
working good.
![image](https://user-images.githubusercontent.com/63460627/84941122-e5894c80-b0ae-11ea-85f2-6b358b71b974.png)
