### ISSUE TITLE
Clear conditional answer if user changes condition to false

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#293]
[AB#10528](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10528)

## What should happen:
In Proposed Development Site, when user switched between Yes to NO to Yes, in Is the Development Site in an Inclusionary Housing Designated Area/Mandatory Inclusionary Housing Area?, previously input data should not be displayed.
## What happened instead:
In Proposed Development Site, when user switched between Yes to NO to Yes, in Is the Development Site in an Inclusionary Housing Designated Area/Mandatory Inclusionary Housing Area?, previously input data is displayed.
## How to reproduce this bug:

Log in to Applicant Portal
Click on the Edit-Pre Application Statement button
navigate to the Proposed Development site
Is the Development Site in an Inclusionary Housing Designated Area/Mandatory Inclusionary Housing Area? input data and save. 
Changed to No  and saved - Is the Development Site in an Inclusionary Housing Designated Area/Mandatory Inclusionary Housing Area?
switched to Yes   Is the Development Site in an Inclusionary Housing Designated Area/Mandatory Inclusionary Housing Area?

![image](https://user-images.githubusercontent.com/63460627/82249222-6968e100-9917-11ea-85c2-96bbccbe1cfc.png)

Changed to No  and saved - Is the Development Site in an Inclusionary Housing Designated Area/Mandatory Inclusionary Housing Area?
![image](https://user-images.githubusercontent.com/63460627/82249271-7ede0b00-9917-11ea-8ee3-bcbb4248c735.png)

switched to Yes   Is the Development Site in an Inclusionary Housing Designated Area/Mandatory Inclusionary Housing Area?
Previously input data Test for Save is displayed.
![image](https://user-images.githubusercontent.com/63460627/82249424-b947a800-9917-11ea-995d-48f72435f8de.png)

**Comment by allthesignals** [comment]
Why?

**Comment by andycochran** [comment]
I think the UI/UX is good as-is. If the user enters text in a conditional input, then accidentally toggles the condition for that question, they don't lose the text they've already entered. 

However, we need to **make sure that the data for the conditional input is not sent to CRM**. We don't want the client sending bad data. It could be misleading to have answers to conditional questions in the data, if the condition for them is false. 

I suggest we repurpose this issue to make sure that a conditional input's data isn't sent to CRM if the condition is false. If the easiest way to do this is by clearing the input when its condition is toggled, I'm okay with the UX/UX changing (but prefer it as-is).

**Comment by hannahkates** [comment]
I agree, Andy. It seems like the real issue here is that the conditional value is still saved on CRM and doesn't get cleared when the user changes their answer to no/false. I've updated the issue name accordingly.

**Comment by allthesignals** [comment]
@andycochran has an idea for this!!!

![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/1924c68c-c08c-4b9d-a8b3-093df08fd9b1)


Complicated but more complex and unnecessary but cool:

```handlebars

            <saveable-form.grouped-radios as |grouped-radios|>
              <grouped-radios.conditional-question @field={{saveable-form.saveableChanges.dcpUrbanareaname}}>
                Urban area name???
              </grouped-radios.conditional-question>
            </saveable-form.grouped-radios>
```

**Comment by Hemachekuri** [comment]
Working good
![image](https://user-images.githubusercontent.com/63460627/84941494-7e1fcc80-b0af-11ea-88a1-af9606c3334a.png)
