### ISSUE TITLE
RWCDS Form Validation

### ISSUE THREAD

**Issue by nnxka** [NYCPlanning/labs-applicant-portal#294]
[Azure Requirement: 10974](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_queries/edit/10974/?triage=true) 
[AB#10974](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10974)
[AB#10976](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10976)
[AB#10994](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10994)
[AB#11028](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/11028)

### User Journey
When a user inputs information that does not meet the form standards, the user should receive an indication that the information they provided is unacceptable. There are two types of validation in this form:
0. Red * if field is required
1. Red "Error" text when a specific field is not completed properly
2. Inability to "Submit" form whenever required fields are not filled out/incomplete

### Display Logic
These are the required fields that must be completed in order to prevent rejection: [spreadsheet link](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/zap/_layouts/15/Doc.aspx?sourcedoc=%7BE0667841-AD0D-41BF-BED0-30114D6D4F03%7D&file=ZAP_RWCDS%20Form%20Field%20Data%20Dictionary_v2.xlsx&action=default&mobileredirect=true)

- [ ] Make sure you check all of the fields required to submit - View the "Form Sections" tab, Column H ("Required")
- [ ] For each of the individual fields, make sure the user is able to only input information that is allowed. 
  - [ ] Data type ("Form Sections" tab, Column I)
  - [ ] Character Maximum ("Form Sections" tab, Columns J)
  - [ ] Option set ("Form Sections" tab, Columns J)
  - [ ] Some of the fields are required based on the conditional question ("Form Sections" tab, Column L)
- [ ] Long text fields should provide the character limit count down

## Unresolved Questions
  - What should the UI for validation look like?

**Comment by godfreyyeung** [comment]
Form sections to validate:
- [x] Project Description (#222)
- [ ] Proposed Actions
- [ ] Analysis
- [ ] Attachments

**Comment by trbmcginnis** [comment]
Proposed Action validations are being handled in separate PR
