### ISSUE TITLE
View-only PAS doesn't provide hyperlinks to documents

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#297]
## Browser(s) and Device(s) observed on:
Chrome, IE, Firefox

## What should happen:
Applicant should be able to View the PDF PAS Form and the document link should be clickable

## What happened instead:
Applicant is not able to view/click on the PDF PAS form generated that is generated CRM, Attached Documents as a whole, after submission are not clickable
## How to reproduce this bug:

1. Log into Applicant Portal
2. Click on the Edit-Pre Application Statement button 
3. Enter any details on the Form and save and submit
4. Log into CRM, navigate to the same project record, same PAS package
5. open the submitted PAS package 
6. Click on the run workflow button, click ok. 
7. wait 2-3 minutes log back into the Applicant Portal, click on the View Pre-Application Portal button for the same project
8. navigate to the attached documents section (error will be seen here)

![image](https://user-images.githubusercontent.com/57362229/82262785-92956b80-992f-11ea-9b99-d7c83b467362.png)

![image](https://user-images.githubusercontent.com/57362229/82262829-a04af100-992f-11ea-81aa-ca772ac2cf29.png)

**Comment by hannahkates** [comment]
The file names are clickable hyperlinks on the edit view. This appears to only be a problem on the view-only page. We need to edit the show.hbs template to provide the file URL.

**Comment by andycochran** [comment]
Addressed by b4ad95e5b2fe182b31c49ea10433a1b81dfb70f5.

**Comment by Hemachekuri** [comment]
Working good

![image.png](https://images.zenhubusercontent.com/5ebc48df610bc025777641a4/c93c0001-ad80-4e60-8cd1-305540d5d4af)
