### ISSUE TITLE
PAS: In Applicant information, ZIP and Phone number should be numeric but it allowing alphabets

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#298]
[AB#10528](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10528)

## What should happen:
In Applicant information, ZIP and Phone number should allow only numbers
## What happened instead:
In Applicant information, ZIP and Phone number should be numeric but it allowing alphabets
## How to reproduce this bug:

Log into Applicant Portal
Click on the Edit-Pre Application Statement button
Enter any details in alphabets on the Form in the applicant section, in zip code and phone numbers

## Browser(s) 
![image](https://user-images.githubusercontent.com/63460627/82264456-f2414600-9932-11ea-87a0-7ae315383f6e.png)
![image](https://user-images.githubusercontent.com/63460627/82264547-18ff7c80-9933-11ea-9a92-5c1dfcb24d7f.png)

**Comment by trbmcginnis** [comment]
Will be solved by completing Issue #313

**Comment by Hemachekuri** [comment]
feild level validations for Applicnat information is as per PAS Form DD
![image](https://user-images.githubusercontent.com/63460627/82366589-68e84d00-99e0-11ea-8cd4-50bfba082109.png)
![image](https://user-images.githubusercontent.com/63460627/82366626-7f8ea400-99e0-11ea-9177-19c169f5ce1c.png)

**Comment by ksinghprod** [comment]
This issue is now fixed

![image](https://user-images.githubusercontent.com/57362229/88095620-68487000-cb63-11ea-8e38-ebf2b9c131ad.png)
