### ISSUE TITLE
When a user removes applicants on the PAS Form they are immediately removed in CRM, not queued for deletion upon "Save"

### ISSUE THREAD

**Issue by bfreeds** [NYCPlanning/labs-applicant-portal#307]
## What should happen:
When a user clicks to remove an applicant or applicant team member, this record should be queued for deletion, triggering a dirty state on the PAS form.  Then, clicking "Save" should fire the api request to remove the applicant in CRM.

## What happened instead:
As soon as a user clicks the remove button, the applicant gets removed in CRM.
![2020-05-19 11 44 25](https://user-images.githubusercontent.com/5316367/82348124-7264bb80-99c6-11ea-8888-4514ce2e72ae.gif)

## How to reproduce this bug:

1. Open a non-dirty PAS Form with applicants on it
2. Click delete
3. Look at network logs or check CRM to see the applicant removed

**Comment by allthesignals** [comment]
Use store.deleteRecord instead of called destroyRecord directly. there might be other options.

**Comment by godfreyyeung** [comment]
I can take a look at this
