### ISSUE TITLE
PAS: Validations for Applicant Team Editor

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-applicant-portal#313]
[AB#10528](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10528)

Need to create changeset validations and include validation messages in the template

Validations should occur on:

- [x] `dcpFirstname`-----------max length: 50------------type: text
- [x] `dcpLastname`-----------max length: 50------------type: text
- [x] `dcpEmail`---------------max length: 50------------type: text
- [x] `dcpZipcode`-------------max length: 5------------type: number
- [x] `dcpCity`-----------------max length: 80------------type: text
- [x] `dcpPhone`---------------max length: 10------------type: number
- [x] `dcpAddress`-------------max length: 250------------type: text

**Comment by trbmcginnis** [comment]
Completing this issue should also resolve Issue #298

**Comment by allthesignals** [comment]
consider reorganizing validations into pas-specific folders:

validations/pas/saveable-form
validations/pas/submittable-form
validations/pas/applicants

**Comment by hannahkates** [comment]
The data type enforcements aren't done / aren't working on develop.
