### ISSUE TITLE
Reorganize Component Files

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicant-portal#329]
![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/d9d125af-1e8f-4203-8468-e179debfdfd9)

Let's meet to discuss how we want to organizze our components. How? domain-specific, reusable, etc?

**Comment by godfreyyeung** [comment]
**Current structure is** 
- components/
  - ... lots of misc ui components (breadcrumbs, character counter, sign in)
  - packages/
    - ... various form components (applicant fieldset, attachments)
    - pas-form/
      - ...edit/show components
  - projects/
    - ... project card components
  - saveable-form/

**Possible proposed structure:**
- components/
  - forms/
    - ... common form components (character counter, applicant fieldset, attachments)
    - pas-form/
      - ... edit/show components
    - rwcds/
      - ... edit/show components
  - projects/
    - ... project card components
  - saveable-form/

**Comment by andycochran** [comment]
Most of the components in the root `components/` folder could be organized into subfolders… 

```
components/
  auth/
    do-logout
    sign-in-button
  ui/
    breadcrumbs-item
    breadcrumbs
    confirmation-modal // Rename confirmation-message (It renders modal and buttons. The "message" is passed to it.)
    page-nav
  messages/
    assistance // Or this could go under ui/ until we have other reusable "messages"
  packages/
    land-use-actions
    project-geography
    proposed-development-types
  saveable-form/
    character-counter
    form-validator
```

This would leave only `saveable-form` and `validation-message` in the root `components/` folder. But `validation-message` seems unnecessary; it only renders a span, invoked in 1 place.

**Comment by allthesignals** [comment]
that looks great!

**Comment by andycochran** [comment]
PR forthcoming…
