### ISSUE TITLE
Investigate Slowness on Dev Server

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicant-portal#330]
What is causing the rebuild/refresh slowness for the dev server? The refresh seems slower than it does for other projects.

**Comment by bfreeds** [comment]
Benchmarks:

Initial Build
![image](https://user-images.githubusercontent.com/5316367/82919914-a438cd80-9f44-11ea-9c0b-92fc517a5484.png)

Hot reloading after initial build
![image](https://user-images.githubusercontent.com/5316367/82920144-ebbf5980-9f44-11ea-80f9-3a4094d21676.png)

**Comment by bfreeds** [comment]
It looks like the rebuild times when changing `hbs` or `js` files is pretty quick, and the bottleneck is primarily being caused by the SASS compiler.  

This is a known, open issue from 2015: https://github.com/adopted-ember-addons/ember-cli-sass/issues/74

**Comment by bfreeds** [comment]
During standup today, @godfreyyeung reported having ~6 second rebuild times.  Need to examine packages and what might be different from Zola (which doesn't have such a slow rebuild).

**Comment by bfreeds** [comment]
Checking ZOLA to see if there's differences in observed performance and project setup:

![image](https://user-images.githubusercontent.com/5316367/83155574-5f8d6d80-a0cf-11ea-807a-cc68e8f455ed.png)

Rebuilding after change to template:
![image](https://user-images.githubusercontent.com/5316367/83155778-96638380-a0cf-11ea-90e2-fc0a64dfe01b.png)

Rebuilding after change to SASS
![image](https://user-images.githubusercontent.com/5316367/83155874-b135f800-a0cf-11ea-86a6-0280ae08f57c.png)

**Comment by bfreeds** [comment]
We should track this open PR, which I _think_ will improve sass compile time:  https://github.com/adopted-ember-addons/ember-cli-sass/pull/215.

The other path for investigating is to hook up `brocolli-inspector` to get a deeper look at what the problem areas are.  @allthesignals I'm not sure how the [Usage](https://github.com/gabrielcsapo/broccoli-inspector#usage) fits with our monorepo, where the `server/index.js` the setup requires would go.

**Comment by allthesignals** [comment]
@bfreeds we could try to install that branch of ember-cli-sass on our project and see if it addresses the issue.

**Comment by allthesignals** [comment]
We cut down the rebuild time significantly. Closing for now but could improve the SASS build time issues in the future.
