### ISSUE TITLE
PAS: Upon Submission of PAS Form, the State is not being displayed correctly, it seems to display the Database option number

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#341]
[AB#10747](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10747)

## Browser(s) and Device(s) observed on:
Chrome, IE, Firefox 
## What should happen:
when an applicant adds/enters information in the applicant team section and saves and submit, the same information should be displayed upon submission

## What happened instead:
Upon Submission of PAS Form, the State is not being displayed correctly, it seems to display the Database option number

## How to reproduce this bug:

1. log in to the App Portal
2. Click on the Edit Pre-Application Statement button 
3. add applicant information, save and submit (error will be seen here)

![image](https://user-images.githubusercontent.com/57362229/82583890-b5a76180-9b61-11ea-9af2-fd7abeeffad5.png)

![image](https://user-images.githubusercontent.com/57362229/82583915-c061f680-9b61-11ea-9de6-92c28173d243.png)

**Comment by godfreyyeung** [comment]
I can look into this. The fix should be to use the {{optionset}} helper

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/88097049-97f87780-cb65-11ea-8c6e-1063f6cc8f62.png)
