### ISSUE TITLE
PAS: User is able to submit PAS form without adding one file in Documents section

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#351]
[AB#10745](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10745)

Fixes [AB#12129](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12129)

## What should happen:
At least one file should be added for Submitting the PAS form, there should be a validation message not allowing to submit without adding file(Document)
## What happened instead:
User is able to submit PAS form without adding one file in Documents section
## How to reproduce this bug:

Log in to Applicant Portal
Click on the Edit-Pre Application Statement button
navigate to the Documents section, Do not add any file and click on submit.

**Comment by ksinghprod** [comment]
This issue is now fixed
