### ISSUE TITLE
Remove hyperlinks on view-only PAS

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#352]
[AB#10747](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10747)

## Browser(s) and Device(s) observed on:
Chrome,IE, Firefox

## What should happen:
User should be able to click on the hyperlinks on the questions even after the submission of the the PAS Package 

## What happened instead:
The hyperlinks in the questions after submission of the PAS Form are not working, it takes you back to the top of the form 

## How to reproduce this bug:

1. Log into Applicant Portal
2. Click on the View Pre-Application Statement button (on a submitted PAS Package)
3. Navigate to the questions with hyperlinks and click on the hyperlinks (error will be seen here)

![image](https://user-images.githubusercontent.com/57362229/82687714-a7227e00-9c25-11ea-91fe-c7a3cf5cdc40.png)

![image](https://user-images.githubusercontent.com/57362229/82688082-447db200-9c26-11ea-9235-b850f8ca5ae1.png)

**Comment by hannahkates** [comment]
I think this is Sev 4, since the users have already submitted and no longer need those resources to conduct research.

**Comment by hannahkates** [comment]
@andycochran do you think these should still be hyperlinks on the view only page? The links seem less useful at this stage in submission.

**Comment by ksinghprod** [comment]
this issue is fixed

![image](https://user-images.githubusercontent.com/57362229/86836152-171c8480-c06b-11ea-8f77-0686d22d2eeb.png)
