### ISSUE TITLE
when user inputs  input more than 10 characters and click on bottom arrow in the input box, number is suffixed by e+number

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#360]
## What should happen:
when user inputs  input more than 10 characters and click on bottom arrow in the input box, number is suffixed by e+number should not be displayed
## What happened instead:
when user inputs  input more than 10 characters and click on bottom arrow in the input box, number is suffixed by e+number
## How to reproduce this bug:
Log in to Applicant Portal
Click on the Edit Pre Application form
navigate to the Proposed Land Use Actions and select Zoning Certification and in
How many Zoning Certification actions? - input more than 10 characters and click on bottom arrow int he input box, number is suffixed by e+number

## Browser(s) and Device(s) observed on:
![image](https://user-images.githubusercontent.com/63460627/82931346-c89ca600-9f54-11ea-91b9-25c9bc2bb2ee.png)

**Comment by ksinghprod** [comment]
Extreame Edge case - not accepted a bug
