### ISSUE TITLE
Create RWCDS test projects

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#364]
**Scenarios to capture:**
- RWCDS packages that aren't yet visible to the applicant - want to make sure they don't appear as editable (`dcp_visibility` is either null or "Internal DCP Only")
- RWCDS packages that are ready for the applicant to edit (`dcp_visibility = "Applicant Only"` and package `statuscode = "Package Preparation"`)
- RWCDS packages that have been submitted (`dcp_visibility is "Applicant Only"` and package `statuscode = "Submitted"`)
- RWCDS packages that have a later status (`dcp_visibility is "Applicant Only"` and package `statuscode` = Reviewed-No Revision Required or Approved)

**Visibility options `dcp_visibility`**
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/3767b750-89a3-4faa-8a70-1f50f7449984)

**Comment by godfreyyeung** [comment]
I Created 4 Packages/PAS-Form pairs, one for each scenario above.

- [x] Not yet visible: Inviseable Shellfish Seaport
- [x] Ready for edit: Ceviche Crossing
- [x] Submitted: Bubba Gump Shrimp Company
- [x] Later status: Detlef Schrempf's **New** Shrimp Shop
