### ISSUE TITLE
Create RWCDS route and template w/ header

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#373]
[AB#10973](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10973)
[AB#10995](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10995)

Must include
- Breadcrumbs at top
- Displayed Project ID 
- Displayed Project Name 
- Displayed Form Version Number 
- Displayed Borough
- Template placeholders for form sections
  - Project Description 
  - Proposed Action(s) 
  - Analysis 
  - Attachments

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/3a0b3975-ea09-4f6e-a35e-0cefa36847ba)

**Comment by godfreyyeung** [comment]
I'm going to assume that the "form sections" bullet requirement for this issue is referring to creating placeholder sections in template. The actual business logic of each section will be tackled in other issues.

**Comment by hannahkates** [comment]
@godfreyyeung yes this is just for the placeholders

**Comment by godfreyyeung** [comment]
Hmm @andycochran @hannahkates 
The wireframes say to use `dcp_projectid` for the project number next to the project name. 
I found that `dcp_name` works to display that 9 digit number (e.g. 2020M0449), but `dcp_projectid` gives the crazy guid. 

Just want to confirm its okay to use `dcp_name` instead? 

![image.png](https://images.zenhubusercontent.com/5ced7833554ce77a5db49edf/edc2e8ae-e6c7-4401-9978-fe8ef7359f80)

**Comment by godfreyyeung** [comment]
@andycochran @hannahkates  Also, not sure if I'm overlooking something in the wireframes but where on the page should we display borough?  I am assuming `dcp_borough` is the proper field for borough?
