### ISSUE TITLE
Fix loading spinner for form edit routes

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-applicant-portal#374]
Sometimes it takes many seconds for the page to transition into the PAS form after user clicks "Edit Pre-Application Statement". This may cause the user to click again and trigger a second transition.

**Comment by andycochran** [comment]
I think this might just be a matter of moving `app/templates/pas-form/loading.hbs` to `app/templates/pas-form-loading.hbs`?
