### ISSUE TITLE
RWCDS: API provides actions to the front-end form

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#420]
User first loads RWCDS form and hasn't saved anything yet:
- dcp_projectaction

User has previously saved:
- RWCDS actions entity

View-only:
- RWCDS actions entity

### Attributes
What attributes should the API response include?
### Filter Logic
Which records should be included? Which should be excluded?

**Comment by trbmcginnis** [comment]
Closing this because duplicate of #223
