### ISSUE TITLE
PAS: "Submit" PAS button either doesn't work or prompts Windows File Explorer

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-applicant-portal#434]
Happens on Windows, particularly Internet Explorer

**Step to Reproduce bug:**
- Add "241-251 W 28 Street Parking Special Permit Renewal 2018M0365" project to account through CRM or log into PAS portal using the dcp user testing login credentials

- For more information on how to reproduce this bug, please watch the following video starting at 38m40: [video link](https://web.microsoftstream.com/video/d227667f-4ae1-49c6-bed4-21c2e1f6aaab?st=2320) 

- This additional user also had problems with submitting the PAS form; however, their file explorer did not pop-up (start video at 48m26):
[video link](https://web.microsoftstream.com/video/a6db9694-c590-4e29-97a5-f5e00e9d0793?st=2906)

This may be related to the previously resolved bug #263.

**Comment by godfreyyeung** [comment]
Just tried but couldn't recreate this issue in Browserstack, Windows 10, IE Edge 83.

**Comment by godfreyyeung** [comment]
Just double checked and tried but couldn't recreate this issue in Browserstack, Windows 10, IE Edge 81.

Do we know the specific IE or chrome versions used during testing?

**Comment by ksinghprod** [comment]
@hannahkates 

Tried to reproduce, could not reproduce, it seems to working now. 

If this issue comes up again, try to see if you are able to submit PAS package on the CRM side.
