### ISSUE TITLE
PAS: Attachments unexpected behavior

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-applicant-portal#445]
Clicking "remove document" sometimes removes multiple documents.

For example, in the screenshot below, clicking the X next to `1200px-Garfield_the_Cat.svg.png` causes `testUploadFile.txt` to be marked for deletion as well 

![image.png](https://images.zenhubusercontent.com/5ced7833554ce77a5db49edf/50ca5fc1-f5da-4ee9-87bd-5337167cce1e)

![image.png](https://images.zenhubusercontent.com/5ced7833554ce77a5db49edf/0913dc5f-51b3-4d4d-9e20-bc41b89cf9d2)

**Comment by nnxka** [comment]
This may also be related to another bug that occurred during the PAS submission usability test. Once the user uploaded attachments and "saved" their form, the attachments disappeared. 

**Steps to reproduce bug:**
- Add "241-251 W 28 Street Parking Special Permit Renewal 2018M0365" project to account through CRM or log into PAS portal using the following login credentials: dcpusertesting@gmail.com / Planning123*

- For more information on how to reproduce this bug, please watch the following video starting at 34m50: [video link](https://web.microsoftstream.com/video/a6db9694-c590-4e29-97a5-f5e00e9d0793?st=2090)

**Comment by andycochran** [comment]
I noticed this too. It also seems to break the undo. 

![2020-06-29 14 49 16](https://user-images.githubusercontent.com/409279/86044423-12772100-ba18-11ea-8745-85508975125b.gif)

**Comment by hannahkates** [comment]
@godfreyyeung This may be related to the previously resolved bug #290

**Comment by godfreyyeung** [comment]
Just tried but couldn't recreate this issue in Browserstack, Windows 10, IE Edge 83.

**Comment by godfreyyeung** [comment]
Was able to reproduce this with the following parameters:

 - qa branch (latest commit cd5a9234fa...)
 - Browserstack, Windows 10, IE Edge 81.

**Comment by godfreyyeung** [comment]
Closing this. I verified that that this bug if fixed immediately after introducing changes in PR #451 
https://github.com/NYCPlanning/labs-applicant-portal/pull/451

**Comment by godfreyyeung** [comment]
Closing this. I verified that that this bug if fixed immediately after introducing changes in PR #451 
https://github.com/NYCPlanning/labs-applicant-portal/pull/451

**Comment by ksinghprod** [comment]
This issue is now fixed

When the user clicks on the x for one of the files, only that file go down to the "to be deleted" section

Also, The user is able to successfully delete/remove a single file and multiple files at once

![image](https://user-images.githubusercontent.com/57362229/86965021-ef91ee80-c134-11ea-886c-c4966e9f9ce0.png)
