### ISSUE TITLE
Create new API end point for user's individual project

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#468]
Related to #469

[Azure Requirement](#)

### User Story
As an applicant, I want to see an overview of my project so that I can understand its status and see what materials I need to submit.

### Attributes
What attributes should the API response include?

- **source: dcp_project**
  - dcp_projectname
  - dcp_name
  - statuscode
  - dcp_publicstatus
  - dcp_projectbrief
  - dcp_applicant_customer
- **source: dcp_package**
  - dcp_packagetype
  - dcp_packageversion
  - dcp_statusdate
  - id of package
  - package status to determine icons

### Filter Logic

- dcp_project records WHERE **visibility = 'General Public'**
- dcp_package WHERE **statecode = 'Active' and visibility = 'Applicant Only'**
- dcp_projectapplicant WHERE contact is associated with the project ID and 'Active'. otherwise return false. (already implemented on my project end point)

**Comment by godfreyyeung** [comment]
Going to pick this up. @allthesignals This is my plan so far:

- new GET endpoint on the Project controller
- The Project service will use the provided project id to get the specific project
- It will expand packages and applicants on the project

This will be similar to the crmService.get() Web API request in the `findManyByContactId()` function, only we aren't requesting multiple projects by contact id.

This largely follows existing patterns, but let me know if you have additional thoughts!

**Comment by godfreyyeung** [comment]
Oh, also we should put guards in place to prevent those outside the project team from loading the project, if they're not in place

**Comment by allthesignals** [comment]
> Going to pick this up. @allthesignals This is my plan so far:
> 
> * new GET endpoint on the Project controller
> * The Project service will use the provided project id to get the specific project
> * It will expand packages and applicants on the project
> 
> This will be similar to the crmService.get() Web API request in the `findManyByContactId()` function, only we aren't requesting multiple projects by contact id.
> 
> This largely follows existing patterns, but let me know if you have additional thoughts!

I think this makes sense. You might have trouble expanding more than 1 level deep. In that case you can query for the data a little differently — we do it in a few places to save a network request.


> Oh, also we should put guards in place to prevent those outside the project team from loading the project.
> 
> I think we can do this by just including the filter condition that checks that the current contact is within the associated applicant team. The findManyByContactId() function already does this.

That's a good point. I think we should capture this in a separate issue, though, because it starts to get into "authorization" part of our auth strategy. A guard is a great pattern for that.

**Comment by hannahkates** [comment]
Wireframes: https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP---Applicant-Portal?node-id=0%3A1

It's always the same figma link btw.

**Comment by allthesignals** [comment]
@hannahkates aah forgot, sorry!
