### ISSUE TITLE
Create project route and modify project model

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#469]
Related to #468
[Azure Requirement](#)

### User Story
As an applicant, I want to see an overview of my project so that I can understand its status and see what materials I need to submit.

### [Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP---Applicant-Portal?node-id=0%3A1)

- [ ] Create route `project/[projectid]`
- [x] Modify model: add dcp_publicstatus from dcp_project
- [ ] Load the model into the route

**Comment by trbmcginnis** [comment]
`dcp_publicstatus` already added to model in this PR:

https://github.com/NYCPlanning/labs-applicant-portal/pull/527

**Comment by hannahkates** [comment]
Once this is implemented, the draft PR for #378 will need to be updated to include the real model attributes.
