### ISSUE TITLE
RWCDS: Get data from PAS form for 2 RWCDS questions

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#478]
The initial data from the two highlighted questions should come from the PAS form
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/86ce7b0a-b83f-46f8-8b19-b7d861d9aa03)

**Comment by godfreyyeung** [comment]
This must be a regression if the behavior isn't observed. We implemented this as part of #434 and #427

**Comment by godfreyyeung** [comment]
I just verified that this is working. 
See RWCDS package A98DA9A7-EFC2-EA11-A813-001DD8309F0E
primary contact/applicant is hkates@planning.nyc.gov

https://local.planninglabs.nyc:4200/rwcds-form/A98DA9A7-EFC2-EA11-A813-001DD8309F0E/edit

**Comment by hannahkates** [comment]
Awesome thanks @godfreyyeung ! I didn't realize these features were done already.
