### ISSUE TITLE
RWCDS: Send build year to project record

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#481]
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/2883a034-47ab-46d0-83f2-e7c6aef9b674)

**Comment by godfreyyeung** [comment]
This is also a regression if the behavior isn't observed. We implemented this in #423 https://github.com/NYCPlanning/labs-applicant-portal/pull/423

**Comment by godfreyyeung** [comment]
I also just confirmed this is already implemented.
![image.png](https://images.zenhubusercontent.com/5ced7833554ce77a5db49edf/60bf8982-444d-40ef-9436-d17b9457df81)
