### ISSUE TITLE
PAS: The project name field is getting populated with the Project ID, Upon submission, the Project Name changes to the Project ID.

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#493]
Browser: Chrome,Firefox, IE

The project name field is prepopulated with the Project ID, which seems to serve the same function as the "revised Project name" field from before. Upon submission, the Project Name changes to the Project ID.

![image](https://user-images.githubusercontent.com/57362229/87348744-390e7f00-c523-11ea-9e3c-8b50eb1a062b.png)

**Comment by allthesignals** [comment]
What should the behavior be?

**Comment by allthesignals** [comment]
Our code pre-populates the revised projectname with `dcp_projectname` value field — should it be some other field that it pre-populates with? 

![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/e1301603-d9b7-4d06-bb86-a769d0e9b6e4)

**Comment by ksinghprod** [comment]
@bean75 

Shouldn't it be the name of the project?

**Comment by allthesignals** [comment]
I have a PR up. I think we thought we were getting the project name with that value in CRM, but that value is actually the project ID.

**Comment by ksinghprod** [comment]
This issue is now fixed

![image](https://user-images.githubusercontent.com/57362229/88095279-dccedf00-cb62-11ea-9ece-bfd17d0cdfd6.png)
