### ISSUE TITLE
Identify/create test projects in CRM

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#5]
We need to work with Aline to setup some basic applicant test data in CRM.

Komal might also be able to help here.

Update: Here's the process for creating test applications:

To create an application:

1. Find a project
2. Click Team
3. Add a contact to the Applicant Team section
4. Make sure the project visibility is "Applicant Only"
5. Make sure there is a "PAS" (Pre-Application Statement) Milestone available

This should be enough to get applications to appear!

**Comment by allthesignals** [comment]
E-mailed Komal on this

**Comment by ksinghprod** [comment]
@hannahkates @allthesignals Hi, 

You can stop by my desk any time and we can walk through this 

Thanks,
Komal

**Comment by allthesignals** [comment]
I was able to do this easily, here's what I found thanks to @ksinghprod: 

Here's the original MS-built portal: https://dcppfsuat2.dynamics365portals.us/applicants/overview/application-status-new/

This might give you some insights into how they fetch data.

To create an application:

1. Find a project
2. Click Team
3. Add a contact to the Applicant Team section
4. Make sure the project visibility is "Applicant Only"
5. Make sure there is a "PAS" (Pre-Application Statement) Milestone available

This should be enough to get applications to appear!

**Comment by allthesignals** [comment]
@ksinghprod it may be to early to ask this, but what are some more realistic test scenarios for PAS? What are some other ways of setting this up so that we have more use cases to deal with?

**Comment by allthesignals** [comment]
Data for edge cases:

> dcp_projectapplicant:
> contact = contactid
> AND statuscode = ‘Active’ // 
> 
> dcp_project:
> statecode = ‘Active’
> AND dcp_visibility IN (‘Applicant Only’, ‘General Public’)

contacts with Inactive statuscodes
dcp_projectapplicants with inactive statuscodes
projects with inactive status codes
projects having visibility statuses other than (‘Applicant Only’, ‘General Public’)


> Editable if....
> 
> PAS package:
> statuscode IN (‘Saved’, ‘Package Preparation’)
> AND dcp_visibility IN (‘Applicant Only’, ‘General Public’)

packages having status codes other than (‘Saved’, ‘Package Preparation’)


> Viewable if…
> PAS package:
> statuscode IN (‘Submitted’, ‘Under Review’, ‘Revision Required’) **
> AND dcp_visibility IN (‘Applicant Only’, ‘General Public’)
> ** All statuscodes except for ‘Mistake’

statuscodes having statuses other than (‘Submitted’, ‘Under Review’, ‘Revision Required’)
dcp_visibility other than (‘Applicant Only’, ‘General Public’)

> If PAS package does not exist or isn’t visible, the project doesn’t get a button

**Comment by allthesignals** [comment]
@bfreeds can you share out how to create more package "Revisions" so we can see how that appears in the JSON response?

**Comment by allthesignals** [comment]
Need to learn from @ksinghprod how to advance a package revision so that we can test the output in the API.

**Comment by ksinghprod** [comment]
@allthesignals @bfreeds We can schedule something tomorrow and I'll be happy to share what i know with you

**Comment by allthesignals** [comment]
@bfreeds hey, can you share out what you learned from this meeting in the issue? I think then we can close it :)

**Comment by bfreeds** [comment]
## Revision Loop Process
We started by creating a new project (ID `2020K0398`)
1. Created an `action`
    - type = `uk` for "unknown"
    - This generates relevant `milestones` for a `uk` action.
      - ![image](https://user-images.githubusercontent.com/5316367/75924051-452b5700-5e34-11ea-962b-d34d5168bdb5.png)
1.  Go to generated milestone `UK - Review Pre-Application Statement`
    - ![image](https://user-images.githubusercontent.com/5316367/75924209-83c11180-5e34-11ea-9b08-73923ddcaaea.png)
1. Go to generated task `Review PAS for Fatal Flaws`
    - Change `outcome` to `Fail` starts the "revision loop". 
    - ![image](https://user-images.githubusercontent.com/5316367/75926363-6b52f600-5e38-11ea-93a5-e04e43e00b4d.png)

Setting the task outcome to fail begins a revision loop.  

The revision loop:
- Sets Action `Status` and `Status Reason` fields = `Completed`
- Sets the related PAS Package 
    - `Package Status Reason` = "Pending Revision"
    - `Package Status` = "Inactive" 
- Creates  
  - **New PAS Package**, which is a copy of the previous PAS Package (increases `Package Version` by 1, and creates a package name that reflects this, like `projectid - packagename - version#`
      -   ![image](https://user-images.githubusercontent.com/5316367/75926668-f03e0f80-5e38-11ea-8a10-8e015f85db73.png)

**Comment by allthesignals** [comment]
Thanks @bfreeds! Going to advance this issue nearer to a "done" state

**Comment by bfreeds** [comment]
Thanks @allthesignals.  @ksinghprod covered _a lot_ in the walkthrough yesterday so I was just going to ask him to check what I understood from it and make sure it's accurate / if it's missing anything.

**Comment by allthesignals** [comment]
Closing
