### ISSUE TITLE
Increase security around access to project materials

### ISSUE THREAD

**Issue by nnxka** [NYCPlanning/labs-applicant-portal#506]
- encrypt/hash CRM IDs so that IDs used in app are not the same -- use API to unhash IDs or use ULURP ID instead
- Make sure url includes an alias rather than unique id

###Unresolved Questions
- Can another user guess the URL and have access to the project?
- Is it possible to look up a unique package based on attributes rather than ID?

**Comment by allthesignals** [comment]
> * Can another user guess the URL and have access to the project?

In terms of guessing, I'm not sure. Brute-force attack would be pretty easy if IDs in CRM follows a certain pattern (I've noticed it does). But I couldn't say how long that sort of attack would take.

Something like [rainbow table](https://en.wikipedia.org/wiki/Rainbow_table) also seems possible. We could ask @CeciliaCY !

If the user is logged in and they guess the URL, they will have access to the editing packages. I think the solutions proposed in this issue would address this, however. A fully-realized authorization strategy would also prevent this.

> * Is it possible to look up a unique package based on attributes rather than ID?

Hmmm... if I'm following, yes — "creeper mode" email param allows this.

**Comment by CeciliaCY** [comment]
@allthesignals , what's the URL pattern here? If it follows a certain pattern, then either brute-force or rainbow table attack is possible to find out the url.

**Comment by allthesignals** [comment]
> @allthesignals , what's the URL pattern here? If it follows a certain pattern, then either brute-force or rainbow table attack is possible to find out the url.

Gotcha. I mean those GUIDs in CRM. I'm not sure how they're generated, if they're some kind of byte sequence or whatever. If they follow a sequence, a user could easily traverse up and down if the sequence is predictable.
