### ISSUE TITLE
Improve Error logging infrastructure 

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-applicant-portal#526]
Let's improve the robustness of our backend error logging and its passing error messages to the frontend.

Ideas:
  - Standardize format of all our thrown HttpExceptions. 
    - This PR contains a proposed format: https://github.com/NYCPlanning/labs-applicant-portal/pull/92
  - Standardize the codes that we assign to our exceptions. 
      - e.g. `<SHORT_DESCRIPTION>_<FUNCTION>`
      -  e.g.  `GET_PROJECT_SERVICE`

Questions:

 - Will thrown HttpExceptions from multiple layers get logged and passed to the frontend?
    - E.g. Say there is a try/catch in a controller endpoint, and it calls a service that also contains a try/catch. If an error occurs within the service, will the HttpExceptions thrown from both the service and parent controller be visible?
      - Should we only throw HttpExceptions at the "leaf-level" layers like service? Or only throw them at root level layers like the controller?

**Comment by hannahkates** [comment]
Related to #170

**Comment by hannahkates** [comment]
This was 21 story points.
