### ISSUE TITLE
RWCDS: Submitted attachments don't appear on view-only template

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#531]
## What should happen:
After the applicant submits their RWCDS, they should be able to access with view-only version which includes links to the attached files they submitted.

## What happened instead:
The Attachments section is blank. It should include any files the user uploaded, as well as the CRM-generated PDF of the submission.
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/43cbfc85-079b-4954-8d6e-6911a13416ce)

## How to reproduce this bug:

Example: https://develop.applicant-portal.planninglabs.nyc/rwcds-form/64222AA8-DDC5-EA11-A813-001DD8309F0E

1. Submit a package with attachments
2. Look at the view-only version
3. See that attachments section is blank.

**Comment by allthesignals** [comment]
Additionally: make validated through the changesets
