### ISSUE TITLE
The "What is the title for the section of the Zoning Resolution that this action is pursuant to?" fields answer does not transfer to CRM's RWCDS form

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#552]
Browser: Chrome

Project Name: Sprint N Testing, 2021Q0124

The "What is the title for the section of the Zoning Resolution that this action is pursuant to?" fields answer on the proposed actions section, does not transfer to CRM's RWCDS form

Not sure exactly to what field on CRM it should transfer  

![image](https://user-images.githubusercontent.com/57362229/88420590-1a2aab00-cdb5-11ea-9816-ed3c6d591138.png)

![image](https://user-images.githubusercontent.com/57362229/88420670-3dedf100-cdb5-11ea-8e7d-9769ba1dacb0.png)

![image](https://user-images.githubusercontent.com/57362229/88420803-7392da00-cdb5-11ea-8aa1-eecc49f0136d.png)

**Comment by trbmcginnis** [comment]
That "What is the title for the section..." question is referring to `zrSectiontitle` which is appropriately filled out here when a user submits the RWCDS form. 

![zrsectiontitle.png](https://images.zenhubusercontent.com/5ca36b1555cfe32f2f66b411/f90bf0b4-8703-4bc5-a828-af6d3633918f)

**Comment by trbmcginnis** [comment]
`dcp_includezoningtextamendment` being handled in #560

**Comment by nnxka** [comment]
This question may be referring to a different attribute within CRM @ksinghprod

**Comment by ksinghprod** [comment]
This issue is working fine, as designed  

![image](https://user-images.githubusercontent.com/57362229/89050203-67140180-d320-11ea-9d80-76622bc783d1.png)


![image](https://user-images.githubusercontent.com/57362229/89050082-37fd9000-d320-11ea-8b06-00c99a592b76.png)
