### ISSUE TITLE
Convert "anchor"-element buttons to button-element buttons

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicant-portal#56]
@allthesignals I think the layout in the sign-in button component needs to be adjusted (from Netlify preview):
![2020-04-06 17 55 09](https://user-images.githubusercontent.com/5316367/78609013-d32d9f80-782f-11ea-96a3-c568e986ae96.gif)

_Originally posted by @bfreeds in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwNDQxMTE4NA==/comments/review_comment_

**Comment by andycochran** [comment]
This should be fixed by the [1.0.7 patch of nyc-planning-style-guide](https://github.com/NYCPlanning/nyc-planning-style-guide/commit/7b6fe495e1422bdadd4ce7d37d68c3cbcf365bb7). An `rm -rf yarn.lock node_modules/` and a fresh `yarn` should solve this.

**Comment by allthesignals** [comment]
sweet! thanks @andycochran
