### ISSUE TITLE
Spike: NYC.ID SAML Implementation

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#561]
1 day to research SAML and determine if the benefits are worthwhile. Decision point at end of day 1.
2 days to test build implementation.

**NYC.ID SAML Implementation Questions:**
- Will it let us control the account creation process?
- Will it let us control the UI for user logging in (login form page)?
- Can users reset their password within our app interface?
- Can users edit contact info within our app interface?
- Can our app/API update the NYC.ID account info? I.e. email, name, phone number

**Comment by allthesignals** [comment]
> Will it let us control the account creation process?

There is no account creation API. We cannot own the UI aspect of account creation. We may only send users to the [registration page](https://www1.nyc.gov/assets/nyc4d/html/services-nycid/registration.shtml).

One thing we can do, however, is send users to a _pre-filled_ account creation page. We could pre-fill an e-mail address in a registration link, for example, and the user would be required to register with the e-mail provided on that page. We could also pre-fill other things on the page, such as First Name and Last Name:

![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/80188174-9bae-4ec4-877e-a7469d4fc752)

We could also hide these fields.

Additionally, with a SAML implementation, we could override the logo with our own.

> Will it let us control the UI for user logging in (login form page)?

Yes, but it appears to be [deprecated](https://www1.nyc.gov/assets/nyc4d/html/services-nycid/authenticate.shtml). I've reached out to see if there's a replacement API and to see the deprecation timeline.

> Can users reset their password within our app interface?

No. This is handled through their UI. However, we can insert a banner with the correct SAML implementation.

> Can users edit contact info within our app interface?

You mean in CRM? We can edit anything in CRM. Our app cannot programmatically change information on NYC.ID, however.

> Can our app/API update the NYC.ID account info? I.e. email, name, phone number

No. This is handled through their UI. Again, we can insert our own banner into their page, but need correct SAML configuration.

**Comment by allthesignals** [comment]
Next steps for me are to figure out how easy it is to configure the SAML requirements so that we can control the banner on the login/registration page.

**Comment by allthesignals** [comment]
I've been responding to some concerns raised in this doc: https://docs.google.com/document/d/1F_xV7BPCrDPjcS_55iw8kbzPOtn3Yl0AZWVSJrcFUQ0/edit#
