### ISSUE TITLE
The Project Id nor the Version number are displayed on the submitted RWCDS from

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#575]
Browser: Chrome 

Project: Sprint N testing 

The Project Id nor the Version number are displayed on the submitted RWCDS from. Not sure if this is by design 

![image](https://user-images.githubusercontent.com/57362229/88970231-0c2acd80-d280-11ea-8352-e2c990d4026c.png)

![image](https://user-images.githubusercontent.com/57362229/88970268-19e05300-d280-11ea-9217-d6c86a197be9.png)

**Comment by godfreyyeung** [comment]
This was recently taken care of in PR #605 for issue #576 ! :) 🎉   
https://github.com/NYCPlanning/labs-applicant-portal/pull/605

**Comment by ksinghprod** [comment]
This issue is now fixed
cc: @B-o-s-s-e-s 

![image](https://user-images.githubusercontent.com/57362229/90539094-69ae8d80-e14d-11ea-8593-39b1cc119adf.png)
