### ISSUE TITLE
The RWCDS package Status reason is not displayed on the Applicant Portal

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#576]
## Browser
Chrome 
## Project Name 
Sprint N Testing 

The RWCDS package Status reason is not displayed on the Applicant Portal

![image](https://user-images.githubusercontent.com/57362229/89055181-fe308780-d327-11ea-9b35-8e7cde7cf656.png)

![image](https://user-images.githubusercontent.com/57362229/89055231-10122a80-d328-11ea-8037-587872e2a4d6.png)

![image](https://user-images.githubusercontent.com/57362229/89055294-2324fa80-d328-11ea-9422-629e51c82be0.png)

**Comment by nnxka** [comment]
Solution: 
- Add Status Reason to RWCDS package display

![image.png](https://images.zenhubusercontent.com/5e8b812e9ded51da8a04d7ae/bfbc2b3a-0aaa-4d1b-9740-f6c105c5d8b0)

**Comment by trbmcginnis** [comment]
We're currently displaying the package's `statuscode` as icons to the left of the package link. Maybe we should also list out the status value (e.g. "Package Preparation", "Submitted", "Under Review", "Reviewed - Revisions Required", "Reviewed -- No Revision Required") in the text next to the link.

@andycochran What do you think?

**Comment by andycochran** [comment]
I don't think it's valuable to display the `statuscode` text to the user. The icon should suffice.

**Comment by godfreyyeung** [comment]
Do you all think we should have the statuscode display on the PAS form as well?

**Comment by ksinghprod** [comment]
Closing this bug as per andy's comment, If this comes up as a usability issue then this will be revisited 

CC @B-o-s-s-e-s
