### ISSUE TITLE
The "Listed below are the actions involved in this project" data is not displaying on the submitted RWCDS Form

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#582]
## Browser 
Chrome

## Project
Sprint N Testing 

## Issue
The "Listed below are the actions involved in this project" data is not displaying on the submitted RWCDS Form

The Action(s) that were pre-populated on the RWCDS from in the Proposed Actions Sections AND the "Which sections of the Zoning Resolution does this modify?", "What is the title for the section of the Zoning Resolution that this action is pursuant to?" fields are not displaying on the submitted RWCDS form 

![image](https://user-images.githubusercontent.com/57362229/89200660-56f95d80-d57e-11ea-92a2-ccaa93c230a4.png)

![image](https://user-images.githubusercontent.com/57362229/89200720-69739700-d57e-11ea-838b-35b8833566aa.png)

**Comment by nnxka** [comment]
- Check if this is missing from the template
- Check if there is an error on how this feature was implemented

**Comment by ksinghprod** [comment]
This issue is now fixed 

cc @B-o-s-s-e-s 

![image](https://user-images.githubusercontent.com/57362229/90540871-d0cd4180-e14f-11ea-8934-99f89ca571d7.png)
