### ISSUE TITLE
The Submitted RWCDS Form is displaying the "Why the project is the same as the propsed With-Action scenario" conditional field in the Analysis section when the user selected no

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#583]
Fixes [AB#12126](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12126)

## Browser
Chrome

## Project 
Sprint N Testing 

## Issue

The Submitted RWCDS Form is displaying the "Why the project is the same as the propsed With-Action scenario" conditional field in the Analysis section when the user selected no

When the user selects no to the "Is the proposed project the same as the proposed With-Action scenario?" The highlighted field in the second screenshot should not appear on the submitted RWCDS Form, or it should say N/A

![image](https://user-images.githubusercontent.com/57362229/89202327-c6704c80-d580-11ea-82ac-30f6f8d9106f.png)

![image](https://user-images.githubusercontent.com/57362229/89202424-eacc2900-d580-11ea-84cc-81237e13b34b.png)

**Comment by nnxka** [comment]
- check logic on template

**Comment by ksinghprod** [comment]
This issue is now fixed 

cc @B-o-s-s-e-s 

![image](https://user-images.githubusercontent.com/57362229/90539326-aed2bf80-e14d-11ea-8e7b-cec9f2847e6c.png)
