### ISSUE TITLE
The ZAP Search Hyperlink is not behaving properly on the Public Status field on the project page 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#585]
[AB#11526](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/11526)

## Browser 
Chrome

## Project
1045 Atlantic Avenue 

## Issue 
The Hyperlink on the Public Status field is not taking the user to the ZAP Search Record when the Public Status of the project is Filed and the project visibility is general public. It takes the user to the same project record in a new window (which is not the same as the project record in ZAP Search)

![image](https://user-images.githubusercontent.com/57362229/89221176-d6982400-d5a0-11ea-85bf-8ea611ad472d.png)

Takes the user to 

![image](https://user-images.githubusercontent.com/57362229/89221220-e9125d80-d5a0-11ea-932a-b02edbcfc74d.png)

![image](https://user-images.githubusercontent.com/57362229/89221332-1b23bf80-d5a1-11ea-8fd0-0f5127055f18.png)

**Comment by nnxka** [comment]
- check url

**Comment by ksinghprod** [comment]
This issue is fixed
