### ISSUE TITLE
The User is not able to save an uploaded document on the RWCDS From

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#589]
## Browser
Chrome, IE, Firefox

## Project Name
Sprint I Bug Fix Test

## Issue

When the user clicks on the upload button to upload a document, the upload button works fine but when the user selects a file from his/her computer to upload, the save button does not work 

![saving Documents](https://user-images.githubusercontent.com/57362229/89323291-731afe80-d653-11ea-8b7a-6eb6c483fc35.gif)

**Comment by godfreyyeung** [comment]
Thanks so much @ksinghprod , great catch

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/90413828-005f4980-e07d-11ea-8fa8-3bb541f0042d.png)
