### ISSUE TITLE
The PDF RWCDS form generated by CRM is not appearing on the RWCDS Form 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#590]
Fixes [AB#12125](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12125)

## Browser
Chrome

## Project
Sprint I Bug Fix Test

## Issue
The PDF RWCDS form generated by CRM is not appearing on the RWCDS Form 

![image](https://user-images.githubusercontent.com/57362229/89323981-8a0e2080-d654-11ea-9b54-48281e914a6d.png)

![image](https://user-images.githubusercontent.com/57362229/89324017-96927900-d654-11ea-95e5-bb2f92f5b06e.png)

## Steps to reproduce if needed
1. submit the RWCDS from the applicant portal
2. navigate to the same project on CRM
3. Click on the Packages tab
4. click on the submitted RWCDS package
5. click on the Flow button, located on the ribbon (see below image)
6. Click ok and wait about 2 minutes 
7. click on the related tab and then click on documents (you will see the PDF RWCDS form, that same form should appear on the submitted RWCDS form on the applicant Portal)

**NOTE** This was working until last friday

![image](https://user-images.githubusercontent.com/57362229/89324058-a4e09500-d654-11ea-9da4-389ba4e817d6.png)

**Comment by godfreyyeung** [comment]
AppDev is currently addressing it, estimating a fix by tomorrow. Will review this again afterwards

**Comment by nnxka** [comment]
This issue was resolved in 9/21/2020. See [this link](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/12125) for more information
