### ISSUE TITLE
Research difference between reports and saved advanced finds

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicant-portal#6]
In MS is there a difference between these two features? Is one faster (cached) than another? Work with Bujji to find out!

**Comment by allthesignals** [comment]
@trbmcginnis would you be interested in giving this a look? These are two different features in CRM we want to explore.

I think @CeciliaCY Bujji and @ksinghprod would be good to loop in on this.

Saved advanced finds would be used in this way: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/retrieve-and-execute-predefined-queries

I don't know what "reports" are or how they are used. @rtblair, maybe you can refresh our memories?

**Comment by ksinghprod** [comment]
Hi @allthesignals @trbmcginnis i sent you one email regarding this

**Comment by allthesignals** [comment]
> Advance find is basically a query to find a desired data set. You can save that particular view so that you do not have to search it every single time. For example when search for packages
>                               package status reason = active
>                               create by = Matt
>                               
> This will produce a result containing a data set of all packages that are active and were created by Matt, you can then save that "query" as a view so you do not have to manually type the query out again and again. That view can be found under project>project (under the list of all of the views, under my views)
>                              
> 
> 
>  and reports are something that was built custom by MCS that are always there in the system, you have to run it (real time). For Instance, The project timeline report is always present on the milestone tab in CRM.

**Comment by bean75** [comment]
If it helps... MCS used views heavily in their design of the portal - all the lists of projects, packages milestones, etc came from views  - it also allowed for displaying certain data associated with the list of items. Their views may be reusable since the requirements are the same.

**Comment by allthesignals** [comment]
@bean75 that's super helpful! do you know how we find those views? are they visible to admin users?

**Comment by bean75** [comment]
They are system views so everyone should be able to see them - On the project they are labeled as such, "Portal - Active Projects for Applicants" may be a good place to start. Note they filtered based on the logged in user, I am not sure if that filter would translate to the login you are using.

**Comment by allthesignals** [comment]
Thanks @bean75 !
