### ISSUE TITLE
Update email address users send questions/feedback to

### ISSUE THREAD

**Issue by bfreeds** [NYCPlanning/labs-applicant-portal#70]
From demo:
>We should use the ZAP_Support_DL for the contact info

**Comment by bfreeds** [comment]
@hannahkates toward the end of the demo it seemed like this became less clear - can you confirm which email should be used?  Open PR for this change if it does need to be switched to `zap_suppport_dl`

**Comment by hannahkates** [comment]
@bean75 Do you have a final decision on whether we should provide zap_suppport_dl or zap_feedback_dl for the email?

**Comment by bean75** [comment]
Yeah - the feedback one is ok.
________________________________

**Comment by hannahkates** [comment]
Okay thanks - closing this issue.
