### ISSUE TITLE
Research if we can use a "snapshot" feature to rollback server

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicant-portal#8]
For testing purposes, it would help if we could find a way to rollback the UAT2 environment to a previous "snapshot" of the CRM state.

If this is true, I would like to have a separate automated-test CRM environment where we can reset things.

If you can't do a snapshot rollback, maybe we can just write a script that builds and tears down data scenarios.

Escalate this question to "Microsoft Premier Support" to get a firm no. 

Roll the containerization feature question into this. Maybe approach to question is not to be prescriptive, but provide requirements "We want to continuiously test against a fresh environment"

**Comment by allthesignals** [comment]
https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments

**Comment by allthesignals** [comment]
Roll the containerization feature question into this

**Comment by hannahkates** [comment]
Closing, this doesn't feel as relevant now that we get fresh ETLs from Prod every night.
