### ISSUE TITLE
Form Submission Confirmation

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#86]
## User Journey

~After the user clicks Submit, they should be shown a confirmation screen where they can view the content before the final submission.~

When the user clicks "Submit" in the form sidebar, a modal should open showing them a message and allowing them to cancel or confirm submission.

## [Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP---Applicant-Portal?node-id=0%3A1)

~https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/1f4a96a8-bd3f-45e9-89ed-dd8a739f6bf8~

![image](https://user-images.githubusercontent.com/409279/80993208-abb6fc00-8e08-11ea-8b1e-2b9f164c2461.png)

**Comment by andycochran** [comment]
The wireframe screenshot above it out of date. Instead of a confirmation screen, we only need a modal with a warning message about revision loops, a confirmation button, and a cancel button. There's no need for an additional route where the user can view their answers before submitting; they can review their answers on the edit route. So a modal will suffice. We just need to confirm the language for that warning message. Maybe something like… 

> ## Confirm Pre-Applicant Statement submission
> ### Are you sure? 
> Please review your answers before submitting this form. This can not be undone. Once submitted, further changes to this form will require City Planning to initiate a revision loop, creating a new version for you to edit. 
> ### [Submit]  [Continue Editing]

**Comment by andycochran** [comment]
@bean75 @hannahkates  Do you have any thoughts on the language above? Or is there existing copy we might be able to reference?

**Comment by andycochran** [comment]
I've clarified this in the wireframes: 

![image](https://user-images.githubusercontent.com/409279/80988451-8a064680-8e01-11ea-9816-c3a5be9f8fe7.png)

**Comment by bean75** [comment]
I like the "Are you sure?"

Maybe reinforce what might cause us to not accept the form though:
Before submitting, ensure the answers are accurate and complete, and that necessary attachments (including the signature form) have been uploaded. If DCP does not receive enough accurate information to provide guidance, the lead planner will notify you and request the form be resubmitted with needed material(s), corrections, or clarifications.

________________________________

**Comment by andycochran** [comment]
Thanks, @bean75. That copy looks great. I'll update the wireframes.  

@bfreeds I think this is clear enough for us to work on now. The "Submit" button in the sidebar will simply open this modal. And the submit button in the modal will actually do the submitting.
