### ISSUE TITLE
External logged in with hemadcp6@gmail.com and confirmed the email. got the message, Welcome! your account was created, when  I tried log in with the same credentials, and click on submit,  blank page is displayed.

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#89]
Fire FoX browser.
User ID : hemadcp6@gmail.com
Password: Welcomedcp1
Actual results: External logged in with hemadcp6@gmail.com and confirmed the email.
got the message, Welcome! your account was created, when  I tried log in with the same credentials, and click on submit,  blank page is displayed.
Expected: user should be directed to ZAP Application Home Page.
![image](https://user-images.githubusercontent.com/63460627/79262695-b4e32780-7e5f-11ea-93e0-2a19d4daa05b.png)
****
![image](https://user-images.githubusercontent.com/63460627/79262768-cc221500-7e5f-11ea-8288-562752c07c3f.png)

**Comment by hannahkates** [comment]
@Hemachekuri I think this is the same login problem you originally experienced when [creating this other issue (83)](https://github.com/NYCPlanning/labs-applicant-portal/issues/83). hemadcp6@gmail.com wasn't saved on a Contact record in CRM. I have now created one that uses hemadcp6@gmail.com. Can you please try again?

**Comment by Hemachekuri** [comment]
Hi Hannah,

If the user is not saved on Contact record in the CRM, then user should see the message "You are not currently assigned to a DCP Project, please email ZAP_Feedback_DL@planning.nyc,gov for further assistance" But upon login blank page is displayed.

Regards, Hema.
________________________________

**Comment by hannahkates** [comment]
Yes I'm aware that we have not met that requirement. We have not fixed that bug yet. It is already captured in issue #83.

**Comment by Hemachekuri** [comment]
Thank you, Hannah.
________________________________

**Comment by Hemachekuri** [comment]
working good. Hence closed the defect.
![image](https://user-images.githubusercontent.com/63460627/79794938-25d38500-8321-11ea-8d89-22c5daf4c090.png)
