### ISSUE TITLE
A deactivated applicant is able to see the project record

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#90]
Browser: Chrome 

Project name: 401 East 84th Street (2019M0408)

Expected Result: when an applicant is deactivated from the applicant team, he/she no longer see the project on the Applicant portal home page

Actual Result: A deactivated applicant is able to see the project record

![image](https://user-images.githubusercontent.com/57362229/79353995-d0a30800-7f09-11ea-857a-c86a1193c817.png)

![image](https://user-images.githubusercontent.com/57362229/79354133-021bd380-7f0a-11ea-97fd-f0db33d41723.png)

![image](https://user-images.githubusercontent.com/57362229/79354189-15c73a00-7f0a-11ea-9333-e2426ca6431c.png)

**Comment by godfreyyeung** [comment]
The screenshots above seem to show that the applicant is still active. What indicates an applicant is "deactivated"? @hannahkates  @ksinghprod

**Comment by godfreyyeung** [comment]
@ksinghprod  or @hannahkates  can you help me create or point me to a project with a dcp_projectapplicant record with `statuscode = 0` ? I've queried the database, but am not able to find any

**Comment by ksinghprod** [comment]
Hi @godfreyyeung the project Id listed in the issue should have it as well

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/79875357-8ad9ba00-83b7-11ea-9994-246f5445ffdb.png)


![image](https://user-images.githubusercontent.com/57362229/79875209-52d27700-83b7-11ea-84a1-799ba584830f.png)
