### ISSUE TITLE
Use oData service

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-applicant-portal#94]
The queries to the Crm Web Api are getting long and unwieldy.

We need to introduce the oData service that @allthesignals wrote for
labs-zap-api.

See https://github.com/NYCPlanning/labs-zap-api/blob/api-only/src/odata/odata.service.ts
https://github.com/NYCPlanning/labs-zap-api/blob/api-only/src/contact/contact.service.ts

**Comment by allthesignals** [comment]
Closing for now :) I think we realized how the abstraction I wrote actually added more confusion.
