### ISSUE TITLE
The Projects on the applicant portal are not sorting alphabetically, but instead by ascii value 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#97]
Browser: Chrome

The Projects on the applicant portal are sorting not sorting alphabetically, but instead by ascii value 

capital U is listed above lower case t.  U (85) has a lower ascii value than lower case t (116). 

![image](https://user-images.githubusercontent.com/57362229/79611393-887e1400-80c8-11ea-9a8f-cec79eaddc2f.png)

**Comment by ksinghprod** [comment]
This will be covered/fixed in a future sprint

**Comment by Eabrante** [comment]
AB#10848

**Comment by allthesignals** [comment]
Can probably be fixed with this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

**Comment by Hemachekuri** [comment]
working good. 

![image](https://user-images.githubusercontent.com/63460627/82470364-3f3c2e00-9a93-11ea-8548-b1e31835c6c8.png)
